- src/static/css/custom.scss
- src/templates/aids/_search_form.html
Modification des onglets de recherche
> Improve search

- src/backers/management/commands/create_deconcentrated_services_backers.py
Comme son nom l'indique.
https://trello.com/c/YITN71kI/194-cr%C3%A9er-tous-les-apporteurs
> Tâche qui créé des apporteurs

- src/templates/data/doc.html
https://trello.com/c/ptqieQ6Z/193-mettre-%C3%A0-disposition-nos-donn%C3%A9es-pour-la-dreal-na-site-addna
> Mise à jour de la documentation de l'API

- src/geofr/management/commands/import_drainage_basins.py
- src/geofr/management/commands/import_epcis.py
- src/geofr/management/commands/update_communes.py
- src/package.json
Mise à jour des tâches d'import / mises à jour des périmètres géographiques.
https://trello.com/c/J6oAaeYL/195-mettre-%C3%A0-jour-les-p%C3%A9rim%C3%A8tres-g%C3%A9o-fusions-de-communes-etc
* Gestion du nouveau format de fichier pour les bassins versants
* Mise à jour des EPCI en se basant sur les données des gens de l'api geo
* Script de vérification des données communes
> Mise à jour des périmètres géographiques

- Pipfile
- Pipfile.lock
- src/dataproviders/management/commands/base.py
- src/dataproviders/management/commands/import_grand_est.py
- src/dataproviders/management/commands/import_rmc.py
- src/dataproviders/scrapers/grand_est.py
- src/dataproviders/scrapers/rmc.py
- src/dataproviders/utils.py
- src/templates/aids/detail.html
Cette PR implémente des imports de données pour : 
- [Les aides de la région GrandEst](https://www.grandest.fr/aides/)
- [Les aides de l'agence de l'eau RMC](https://www.eaurmc.fr/jcms/gbr_5503/fr/les-aides-financieres-primes-et-appels-a-projets)
Chaque import est divisé en deux parties : 
1) un [spider Scrapy](https://docs.scrapy.org/en/latest/topics/spiders.html) chargé de récupérer les données brutes
2) un script d'import similaire à ceux existants pour l'ademe, la dreal, etc.
> Utilisation de Scrapy pour importer des données

- src/dataproviders/management/commands/import_grand_est.py
- src/dataproviders/scrapers/grand_est.py
Suite au retour d'Élise sur l'import de la région GrandEst, de nouvelles données ont été traitées lors de l'import.
https://trello.com/c/cpZlVQhs/213-tester-scrapy-sur-le-site-de-la-r%C3%A9gion-grand-est
> Importe plus de données de la région GrandEst

- src/package-lock.json
- src/package.json
Corrige quelques alertes de sécu.
https://github.com/MTES-MCT/aides-territoires/network/alerts
> GitHub security issues

- src/aids/admin.py
- src/dataproviders/management/commands/base.py
- src/dataproviders/management/commands/import_dreal.py
- src/templates/aids/_search_form.html
Quelques améliorations liées à la gestion des aap : 
- ajoute une reconnaissance basique automatique des aap lors des imports
- ajoute un filtre dans l'admin
- déplace la case de recherche sur l'accueil du moteur.
> Détection automatique des aap

- src/aids/admin.py
- src/locales/fr/LC_MESSAGES/django.po
En tant qu'admin, je peux tagguer simultanément plusieurs aides comme des AAP
https://trello.com/c/f2HRZe47
> Tagguer simultanément plusieurs aides comme des AAP

- README.md
- deploy.py
Ajoute un raccourci pour déployer plus facilement et éviter les erreurs.
Ajoute une confirmation avant déploiement.
https://trello.com/c/2LgXVFFR/281-mettre-en-place-un-syst%C3%A8me-de-confirmation-avant-les-mises-en-prod
> Raccourci vers script de déploiement

- src/aids/forms.py
- src/locales/fr/LC_MESSAGES/django.po
https://trello.com/c/TkOa8tn9/257-am%C3%A9liorer-la-compr%C3%A9hension-du-formulaire-pour-les-contributeurs
> Mise à jour de labels du formulaire

- src/static/css/custom.scss
- src/static/js/aids/perimeter_autocomplete.js
- src/templates/_base.html
- src/templates/home/_marketing.html
- src/templates/home/home.html
Multiples corrections : 
- Pages d'accueil : Suppression la box " saisissez au moins un caractère" (https://trello.com/c/aUFrhm3Q)
- Newsletter : centrer le texte (comme dans les autres blocs)  (https://trello.com/c/HzIAChC4)
- Page d'accueil : mettre "Recherchez dès maintenant" à la ligne (https://trello.com/c/tPrqaLz2)
- Marketing : (https://trello.com/c/Jp9sVc3F)
- Page d'accueil : tiret entre Aides et territoires "Aides-territoires"
- Partenaires : nommer cette rubrique "Ils sont déjà sur Aides-territoires" (https://trello.com/c/AwyhwU5z)
> Home page evolution 2

- src/aids/forms.py
- src/locales/fr/LC_MESSAGES/django.po
- src/static/js/aids/update_status_form_availability.js
- src/templates/_base.html
- src/templates/aids/edit.html
https://trello.com/c/TkOa8tn9/257-am%C3%A9liorer-la-compr%C3%A9hension-du-formulaire-pour-les-contributeurs
> Clareté du champ "apporteurs"

- src/aids/forms.py
- src/aids/tests/test_search_engine.py
https://trello.com/c/tpkIZkgd/307-le-p%C3%A9rim%C3%A8tre-france-outre-mer-ne-fonctionne-pas
> Problème avec le périmètre « Outre-mer ».

- src/static/css/custom.scss
- src/static/js/aids/enable_softmaxlength.js
- src/static/js/plugins/softmaxlength.js
- src/templates/aids/_base_edit.html
https://trello.com/c/snPdM1Zd/363-titre-de-laide-bug-li%C3%A9-%C3%A0-limport-dune-aide-et-%C3%A0-la-limitation-%C3%A0-180-caract%C3%A8res
Ajout d'un plugin jquery personnalisé pour afficher un compteur de caractères sur le titre.
> Compteur de caractères pour les titres

- src/locales/fr/LC_MESSAGES/django.po
- src/static/css/styles.scss
- src/templates/_checkbox_snippet.html
- src/templates/_field_snippet.html
- src/templates/_form_header.html
- src/templates/aids/_base_edit.html
https://trello.com/c/VUNDEyFe/365-enregistrer-en-brouillon-a-ajuster
* supprime la validation automatique du navigateur.
* ajoute un message en haut de la page en cas d'erreur.
> Corrige les problèmes de validation du formulaire

- src/static/css/styles.scss
- src/templates/_field_snippet.html
https://trello.com/c/95Z4ZAQ3/371-ajustements-du-formulaire-de-publication-daides
> Ajustements du formulaire de publication d'aides

- src/aids/forms.py
- src/static/css/admin.css
- src/static/js/aids/enable_softmaxlength.js
- src/static/js/plugins/softmaxlength.js
https://trello.com/c/UMDouI1A/373-formulaire-champ-titre
> Longueur du champ titre

- src/locales/fr/LC_MESSAGES/django.po
https://trello.com/c/UMq8T7gq/378-17-formulaire-dispositif-applicable-pour-un-projet
https://trello.com/c/XvXqxcQR/379-18-formulaire-types-de-d%C3%A9penses-actions-couvertes
> Quelques traductions

- src/aids/forms.py
> Ajouter un widget markdown pour le champ « contact »

- src/locales/fr/LC_MESSAGES/django.po
- src/static/css/_theme.scss
- src/static/css/custom.scss
- src/static/css/styles.scss
- src/templates/aids/_aid_result.html
- src/templates/aids/detail.html
https://trello.com/c/DLYdBS4V/358-6-formulaire-champ-ou-ajoutez-un-nouvel-apporteur-li%C3%A9-au-point-5-ajout-de-la-notion-dinstructeur-et-de-financeur
> Affichage de l'instructeur sur la page de détail de l'aide

- src/geofr/admin_views.py
https://trello.com/c/2BiN4p6H/405-bug-p%C3%A9rim%C3%A8tre-acv
> Corrige l'import de périmètres

- src/locales/fr/LC_MESSAGES/django.po
Faire apparaître "Ingénierie" devant "financière", "technique" et "juridique" *
https://trello.com/c/dArLNOba
> Faire apparaître "Ingénierie"

- src/templates/home/legal_mentions.html
Modification des mentions légales suite à l'arrivée de la nouvelle directrice
> Changement de directeur de la DGALN

- src/aids/forms.py
https://trello.com/c/0GXLxmTV/413-formulaire-champs-date
> Champ « date d'ouverture » optionnel pour les admins

- src/aids/forms.py
- src/locales/fr/LC_MESSAGES/django.po
Le champ devient  : Autres critères d'éligibilité
https://trello.com/c/KFJKrgO0
> Modification du champ y a-t-il d'autres critéres d'éligibilité

- src/static/css/custom.scss
https://trello.com/c/NECD7jyp/418-bug-graphique-sur-laffichage-du-moteur-de-recherche
> Corrige un mini-bug d'affichage dans le moteur de recherche

- src/aids/forms.py
- src/aids/models.py
- src/aids/tests/test_aid_form_ui.py
- src/aids/tests/test_forms.py
- src/locales/fr/LC_MESSAGES/django.po
- src/static/js/aids/toggle_calendar_related_fields.js
- src/static/js/aids/toggle_subvention_related_fields.js
- src/templates/aids/_base_edit.html
https://trello.com/c/ATf6ZaLM/402-23-formulaire-champ-calendrier-de-laide
> Champs calendrier

- src/aids/forms.py
- src/aids/models.py
- src/locales/fr/LC_MESSAGES/django.po
https://trello.com/c/dArLNOba/415-dans-les-r%C3%A9sultats-faire-appara%C3%AEtre-ing%C3%A9nierie-devant-chaque-type-daides-en-ing%C3%A9nierie
>  Mise à jour des labels pour les aides en ingénierie 

- src/aids/forms.py
- src/templates/aids/_base_edit.html
https://trello.com/c/DpighLHk/377-10-formulaire-champ-sagit-il-dun-aap-ami
> Transforme le champ « S'agit-il d'un aap… ? » en case à cocher

- deployment/roles/appservers/templates/nginx.j2
- src/static/well-known/google7cbe5bb6ac545929.html
https://trello.com/c/gxnf8Psh/433-installation-de-google-search-console
> Activate la validation de Google Search Console

- src/aids/models.py
- src/templates/aids/detail.html
https://trello.com/c/sMOHVURl/440-bug-amender-une-aide
> Cache les actions pour les aides en prévisualisations

- src/aids/admin.py
- src/aids/models.py
- src/aids/tests/test_managers.py
- src/core/admin.py
- src/templates/admin/input_filter.html
https://trello.com/c/6243pkvt/407-ajouter-un-filtre-pour-voir-les-aides-p%C3%A9rim%C3%A9es
https://trello.com/c/tEN5D1nz/429-admin-diff%C3%A9rencier-les-aides-en-cours-sur-le-site-des-aides-cl%C3%B4tur%C3%A9es
https://trello.com/c/SAKgSubc/430-admin-filtrer-par-porteur-daides
https://trello.com/c/Vrat0Pba/431-admin-ajouter-le-champ-date-de-cl%C3%B4ture-de-laide
> Amélioration de l'admin pour les aides

- src/geofr/management/commands/README.md
- src/geofr/management/commands/populate_communes.py
- src/geofr/management/commands/populate_countries.py
- src/geofr/management/commands/populate_departments.py
- src/geofr/management/commands/populate_epcis.py
- src/geofr/management/commands/populate_overseas.py
- src/geofr/management/commands/populate_regions.py
- src/package-lock.json
- src/package.json
https://trello.com/c/XNmiVi3P/366-ajouter-les-p%C3%A9rim%C3%A8tres-g%C3%A9ographiques-des-dom-tom-manquants
> Mise à jour des scripts d'import des périmètres géographiques

- src/core/mail_backends.py
- src/core/settings/base.py
- src/core/settings/production.py
Filtre les emails dont le destinataire ne fait pas partie de la liste blanche.
> Créé un `backend` d'envoi d'email spécial pour le staging

- src/geofr/admin.py
- src/geofr/admin_views.py
- src/geofr/forms/__init__.py
- src/geofr/forms/forms.py
- src/geofr/utils.py
- src/locales/fr/LC_MESSAGES/django.po
- src/static/css/admin.css
- src/templates/admin/geofr/perimeter/submit_line.html
- src/templates/admin/perimeter_combine.html
- src/templates/admin/perimeter_upload.html
https://trello.com/c/UxpbVvFG/437-pouvoir-cumuler-plusieurs-p%C3%A9rim%C3%A8tres-existants-pour-cr%C3%A9er-un-nouveau-p%C3%A9rim%C3%A8tre
> UI de combinaison de périmètres

- src/aids/tasks.py
- src/aids/tests/test_views.py
- src/aids/views.py
- src/core/settings/base.py
- src/core/settings/production.py
- src/dataproviders/tests/test_import_commands.py
- src/templates/emails/log_admins.txt
https://trello.com/c/jYPU2ZML/345-etq-admin-je-veux-%C3%AAtre-au-courant-quand-un-contributeur-supprime-une-aide
> Envoi d'email quand une aide est dépubliée

- src/static/css/admin.css
https://trello.com/c/OlXqGR0H/446-affichage-admin-champs-%C3%A0-agrandir
> Largeur des champs admin

- src/aids/admin.py
https://trello.com/c/2MhFmFmN/460-bug-admin-recherche-par-apporteurs
> Corrige un bug dans la recherch admin

- src/aids/forms.py
https://trello.com/c/SBoHMeoH/462-admin-r%C3%A9currence-calendrier
> Validation du calendrier en admin

- src/aids/admin.py
- src/aids/models.py
- src/locales/fr/LC_MESSAGES/django.po
https://trello.com/c/OISafcz2/479-modifier-la-fonction-supprimer-de-ladmin-des-aides
> Suppression « soft » des aides en admin

- src/locales/fr/LC_MESSAGES/django.po
- src/static/js/aids/toggle_aid_instructor_field.js
- src/templates/_js_i18n.html
- src/templates/aids/_base_edit.html
https://trello.com/c/yk6P7uCw/562-formulaire-changement-texte-condition-de-choix
> Affiche un bouton pour révéler le champ « instructeurs de l'aide »

- src/.env.example
Suppression de la valeur de SECRET_KEY
> fix: remove secrets from code

- LECODE.md
- README.md
- src/accounts/__init__.py
- src/aids/__init__.py
- src/alerts/__init__.py
- src/analytics/__init__.py
- src/backers/__init__.py
- src/bookmarks/__init__.py
- src/bundles/__init__.py
- src/core/__init__.py
- src/data/__init__.py
- src/dataproviders/__init__.py
- src/geofr/__init__.py
- src/home/__init__.py
- src/integration/__init__.py
- src/minisites/__init__.py
- src/pages/__init__.py
- src/programs/__init__.py
- src/search/__init__.py
- src/stats/__init__.py
- src/tags/__init__.py
https://trello.com/c/g8Kt15Wi/624-pr%C3%A9parer-larriv%C3%A9e-de-nouveaux-devs
> Ajoute de la doc supplémentaire pour l'embarquement de nouveaux devs

- ONBOARDING.md
Fix typo in onboarding file (missing -s for French plural)
> Fix typo in onboarding file (missing -s for French plural)

- src/dataproviders/management/commands/import_bpi.py
- src/dataproviders/management/commands/import_grand_est.py
- src/dataproviders/management/commands/import_occitanie.py
Fixes MTES-MCT/aides-territoires#154 (commentaires d'import erronés)
> Fixes MTES-MCT/aides-territoires#154 (commentaires d'import erronés)

- src/aids/forms.py
- src/locales/fr/LC_MESSAGES/django.po
https://trello.com/c/UWqP0jF9/669-renommer-champ-dans-le-formulaire
> Mise à jour d'un label dans le champ « bénéficiaires »

- src/locales/fr/LC_MESSAGES/django.po
- src/templates/accounts/contributor_profile.html
Corrige un simple problème de traduction non prise en compte dans un template.
> Fix a translation problem on contributor profile

- src/aids/api/views.py
https://trello.com/c/NrUTsbsV/677-impl%C3%A9menter-une-nouvelle-entr%C3%A9e-api-par-slug
> Utilise les slugs pour identifier les aides dans l'API

- src/aids/forms.py
- src/locales/fr/LC_MESSAGES/django.po
- src/minisites/views.py
- src/static/js/aids/enable_softmaxlength.js
https://trello.com/c/CbtrtwGE/678-ajustements-de-texte-formulaire
https://trello.com/c/pIxyasME/681-formulaire-modification-des-intitul%C3%A9s
> Mise à jour de quelques labels de formulaire

- deployment/group_vars/prod.yml
- deployment/group_vars/stage.yml
- deployment/roles/appservers/tasks/certbot.yml
https://trello.com/c/fYbLLaLl/659-cr%C3%A9ation-de-5-urls-pages-personnalis%C3%A9es
> Création de nouveaux sous-domaines pour des partenaires

- ONBOARDING.md
- README.md
https://trello.com/c/dQBDMdZb/684-cr%C3%A9er-une-adresse-email-pour-l%C3%A9quipe-tech
> Corrige la doc pour intégrer la mention de l'adresse tech

- src/backers/admin.py
- src/locales/fr/LC_MESSAGES/django.po
Il y avait un problème avec la page admin des porteur d'aides.
> Page admin Backers : Problème de performance

- ONBOARDING.md
Ajout d'une section pour le lancement du serveur de développement des minisites.
> create a section about the local access to minisite

- src/templates/minisites/_css.html
alignement des logos du header sur la ligne du bas.
> AI flex-end logos partners

- src/templates/aids/_base_search.html
Ajout d'un paragraphe dans le template _base_search.html conditionné par la présence du paramètre published_after dans la querystring.
> add request.GET.published_after condition

- src/templates/minisites/_css.html
- src/templates/minisites/_search_form.html
- src/templates/minisites/_sticky-btn.html
- src/templates/minisites/search_page.html
- src/templates/search/search_page.html
Ajout d'un bouton "publier des aides" dans le formulaire de recherche des pages personnalisées.
> add publish-new-aids-btn

- src/templates/minisites/_css.html
- src/templates/minisites/_footer.html
- src/templates/minisites/_header.html
Changement du logo MTES pour le logo RF dans le header, 
Suppression de la div "other-links" dans le footer.
> add RF headerlogo delete footer otherlinks

- src/templates/minisites/_css.html
Ajout margin-top et margin-bottom pour le header des PP
Ajout padding-bottom pour la div all-logos du footer des PP
Font-size 1rem pour le sticky button "publier une aide"
> adjust design PP

- src/aids/views.py
- src/minisites/mixins.py
- src/minisites/views.py
Pour que la recherche avec plus de critère utilise elle aussi une version du formulaire où les champs structures et thématique sont limités à ce qui a été choisi dans l'admin.
> Minisite advanced search

- ONBOARDING.md
Ajout d'une section sur le lancement des tests avec indications sur la config de la base de données
> add test section

- src/static/css/_custom.scss
- src/templates/aids/_search_form.html
Re-alignement centré des blocs du cartouche de recherche sur la page de résultats.
> realign form-container elements

- src/static/css/_custom.scss
- src/static/css/_globals.scss
Changement de couleur des liens visités de la navbar, du footer et des cartes aides.
> Color visited link

- src/templates/_footer.html
Changement de contenu du paragraphe visant la newsletter dans le footer.
> fix text newsletterfooter

- deployment/group_vars/prod.yml
Ajout d'un sous-domaine france-relance-reunion
> add france-relance-reunion as minisite url

- deployment/group_vars/prod.yml
france-relance-corse
france-relance-occitanie
france-relance-idf
france-relance-aura
france-relance-bfc
france-relance-guadeloupe
france-relance-martinique
france-relance-mayotte
france-relance-bretagne
> Minisites France Relance supplémentaires

- src/aids/admin.py
- src/dataproviders/utils.py
- src/package-lock.json
- src/package.json
- src/pages/admin.py
- src/search/admin.py
- src/upload/settings.py
Pour avoir un redimensionnement possible en tirant sur l'angle de l'image.
> Image dans les champs textes de l'admin : Permettre de redimensionner l'image

- src/aids/api/serializers.py
- src/aids/api/views.py
- src/aids/tests/test_api.py
- src/core/settings/base.py
- src/core/urls.py
- src/data/views.py
- src/templates/data/doc.html
https://trello.com/c/8XP0QGsj/666-documenter-un-versionnement-de-lapi
Implémente un versionnemente de l'API (même s'il n'y a qu'une version pour le moment).
> Api version

- src/aids/api/serializers.py
- src/aids/api/views.py
- src/aids/tests/test_api.py
- src/core/settings/base.py
- src/templates/data/doc.html
https://trello.com/c/dwzm87cG/761-question-pr%C3%A9sence-champ-programs-dans-api
Ajoute le champ `programs` dans l'API aides. Incrémente la version de l'API et met à jour la doc.
> Ajoute le champ « programme » à l'api

- src/locales/fr/LC_MESSAGES/django.po
- src/templates/accounts/login.html
https://trello.com/c/wN4c0N1E/781-page-de-connexion
Mise à jour de quelques textes sur le formulaire de connexion.
> PR Triviale : mise à jour du formulaire de login

- src/static/css/_globals.scss
- src/templates/_anonymous_menu.html
Changement de design du lien "publier une aide" présent dans la navigation du header d'AT. 
https://trello.com/c/BmMHx6Z8/780-item-menu-publier-une-aide
> Change design of publish-aid link in header

- src/aids/admin.py
- src/pages/admin.py
- src/search/admin.py
- src/static/js/enable_rich_text_editor.js
- src/static/js/enable_rich_text_editor_simple.js
- src/static/js/shared_config.js
- src/templates/_base.html
- src/templates/admin/amend_ui.html
- src/templates/aids/_base_edit.html
https://trello.com/c/OYx1HccZ/811-champ-textes-pouvoir-centrer-le-texte-et-les-images
> Possibilité pour les admins de justifier le texte

- deployment/group_vars/prod.yml
Création d'un sous-domaine `https://actioncoeurdeville.aides-territoires.beta.gouv.fr/`
> add PP actioncoeurdeville

- src/aids/admin.py
- src/locales/fr/LC_MESSAGES/django.po
https://trello.com/c/8T6tJKz2/803-am%C3%A9liorations-de-loutil-dexport-xls
dans la continuité de https://github.com/MTES-MCT/aides-territoires/pull/273
- enlève la colonne id
- met à jour la traduction du champs `Destinations` (qui était déjà traduit comme ca dans les forms)
> Admin Export : petites modifs additionnelles

- src/alerts/management/commands/create_alerts_from_csv_file.py
- src/alerts/tests/emails.csv
- src/alerts/tests/test_alert_command.py
- src/alerts/tests/test_alert_create_command.py
- src/upload/tests/test_views.py
https://trello.com/c/sl4vxWA4/682-cr%C3%A9ation-dalertes-pour-la-bdd-addna
Management command pour créer des alertes à partir d'une liste d'emails (csv avec une colonne `email`)
Il y a des exemples d'usage de la commande dans le fichier
Cette commande se veut être réutilisable (si jamais)
Usage premier : création de 2000 alertes sur des aides ADDNA (Nouvelle Aquitaine)
> Import : alertes à partir d'une liste d'emails (fichier csv)

- src/templates/_footer.html
Ecriture inclusive "Restez informé-e-s" à la place de "Restez informés" dans la div Newsletter du footer.
> Ecriture inclusive dans le bloc Newsletter du footer

- Pipfile
- Pipfile.lock
- src/core/settings/base.py
- src/core/urls.py
- src/templates/data/doc.html
Trello : https://trello.com/c/baC6u3SO/650-discussion-am%C3%A9liorer-la-doc-pour-les-utilisateurs-api
Concernant la documentation, je propose ceci :
1. On met en place une documentation auto générée en utilisant swagger : c'est disponible sur l'URL : /swagger/
2. La page de documentation sur l'URL /data/ est consacrée à la doc de l'API de présentation. Dans cette page, on parle de notre licence et on met un lien vers la doc générée.
3. Dans le wiki, on explique aux organismes partenaires toutes les façons possible pour publier leurs aides.
Il faudrait relire ces pages :
- https://staging.aides-territoires.beta.gouv.fr/swagger/
- https://github.com/MTES-MCT/aides-territoires/wiki/Comment-publier-vos-donn%C3%A9es-pour-une-reprise-sur-Aides-territoires
- …
> Mise à jour de la documentation : API + Publication de données

- src/alerts/management/commands/create_alerts_from_csv_file.py
https://trello.com/c/sl4vxWA4/682-cr%C3%A9ation-dalertes-pour-la-bdd-addna
J'ai eu un petit soucis cette semaine lorsque j'ai lancé la commande de création d'alertes à partir d'un fichier CSV, l'argument `latest_alert_date` plantait car il s'attendait à un datetime au lien d'un string. Donc petit fix.
Et j'ai pu créer les alertes quand même (en prod), mais je l'ai fait en 2 étapes : 
- lancé la commande sans l'argument `--latest_alert_date`
- puis modifié à la main la date dans le shell
> Création d'alertes : fix sur l'argument date

- src/backers/admin.py
- src/home/views.py
- src/templates/home/home.html
- Des propositions d'amélioration de l'admin
- Une petite simplification d'une queryset django
- Une vérification de la présence d'image dans le template de la page d'accueil
> Carrousel porteur d'aide : Amélioration admin et revue de code

- src/aids/admin.py
- src/aids/forms.py
- src/static/js/aids/duplicate_buster.js
https://trello.com/c/WkW4LCk8/802-outil-admin-pour-identifier-aides-doublonn%C3%A9es
Ajoute une détection des aides doublonnées dans l'admin.
> Détection des doublons

- src/accounts/forms.py
- src/templates/accounts/register.html
https://trello.com/c/2rPSPTkY/833-cr%C3%A9ation-compte-porteur-daide-mot-de-passe
> Ajout du champ « mot de passe » sur le formulaire d'inscription

- src/templates/minisites/_css.html
- src/templates/minisites/_sticky-btn.html
- Change la couleur du top-footer des PP
- Agrandissement du bouton `publier une aide` pour la version desktop : https://trello.com/c/opSETUBR/826-pp-bouton-publier-une-aide
> Modification design à la marge pour les PP

- docs/releases/2.2.1.md
> Release 2.2.1

- src/accounts/admin.py
- src/locales/fr/LC_MESSAGES/django.po
- src/templates/_footer.html
https://trello.com/c/ewXLfTPY/777-champs-qualifiants-utilisateurs
Ajoute les champs manquants dans l'administration des utilisateurs.
> Ajoute les champs manquants dans la fiche utilisateur

- src/aids/views.py
- src/backers/views.py
Corrige des soucis de style dans les fichiers `backers/views.py` et `aids/views.py`.
> Fix checkstyle

- src/static/css/_custom.scss
- src/templates/backers/detail.html
https://trello.com/c/GEnriKzE/898-ajout-du-logo-du-porteur-sur-la-page-porteur
Sur les pages porteurs, ajout du logo du porteur.
> Ajout du logo du porteur sur la page porteur

- src/locales/fr/LC_MESSAGES/django.po
- src/static/js/aids/programs_autocomplete.js
- src/templates/_js_i18n.html
Dans la continuité de la PR #372 : Modification du placeholder du filtre programme dans le cartouche de recherche. 
https://trello.com/c/YVXRXlxe/897-ajout-du-filtre-programme-dans-le-cartouche-de-recherche
> Modification du placeholder du filtre programme dans le cartouche de recherche. 

- src/aids/api/serializers.py
- src/aids/api/views.py
- src/core/settings/base.py
- src/locales/fr/LC_MESSAGES/django.po
Exporte les catégories dans l'API, et bumpe la version en 1.2.
> Exporte les catégories dans l'API

- src/static/css/_custom.scss
- src/static/css/_globals.scss
- src/templates/aids/_results.html
https://trello.com/c/TD1Gi6u3/899-ajout-dun-bouton-alerte-dans-la-liste-de-r%C3%A9sultats-des-aides
Ajout d'un bloc `#save-alert` dans la liste de résultats des aides.
> Ajout d'un bloc alerte dans la liste de résultat des aides

- src/minisites/views.py
- src/templates/minisites/stats.html
dans la continuité de https://github.com/MTES-MCT/aides-territoires/pull/401
Enlève le count des aides en brouillon ou expirées
> Pages partenaires Stats V2 fix

- src/templates/minisites/_css.html
- src/templates/minisites/_sticky-btn.html
https://trello.com/c/lNq5IbQ4/949-changement-de-lien-sur-les-pp
> Changement d'url pour le lien "publier une aide" sur les PP

- src/aids/mixins.py
- src/aids/models.py
- src/aids/views.py
- src/locales/fr/LC_MESSAGES/django.po
- src/minisites/mixins.py
- src/static/css/_custom.scss
- src/templates/aids/draft_list.html
Au passage, corrige un petit problème de perfs sur la page portefeuille.
> Ajoute de la colonne « visibilité sur le site » dans le portefeuille

- src/static/css/_globals.scss
- src/templates/_footer.html
https://trello.com/c/goSApX8Y/954-ajout-r%C3%A9seaux-sociaux-dans-le-footer
> Ajout des liens réseaux sociaux dans le footer

- src/programs/admin.py
- src/templates/programs/detail.html
> Active l'éditeur de texte riche pour les pages programmes

- src/backers/admin.py
> Pouvoir rattacher des Porteurs à des Groupes de Porteurs

- src/locales/fr/LC_MESSAGES/django.po
Ajout de la traduction manquante de "Your project"
> Ajoute traduction manquante

- src/templates/minisites/_css.html
- src/templates/minisites/_footer.html
https://trello.com/c/kG9LG7zn/977-ajout-liens-dans-le-footer-des-pp
Ajout des liens vers les réseaux sociaux et vers le formulaire d'inscription à la newsletter dans le footer des pages personnalisées. 
Suppression du numéro de téléphone dans le footer.
> Ajout des réseaux sociaux et du lien d'inscription à la newsletter dans le footer des PP

- src/upload/management/commands/update_rich_text_urls.py
Remplace les urls `/media/…` par des urls vers S3.
> Mise à jour des urls dans les champs de texte riche

- src/scalingo.json
Réduire la voilure de nos Review Apps, avoir des containers S par défaut (au lieu de M)
Doc sur le sujet : https://developers.scalingo.com/scalingo-json-schema/index
> Redimensionnement les containers des "app review"

- src/templates/home/home.html
https://trello.com/c/zuX8SvvC/1038-texte-home-page
Remplace le texte : "Les aides sont présentées et diffusées inégalement selon les porteurs" par  “Les aides sont diffusées par leurs porteurs”
> Changement de texte sur la page Home

- src/static/css/_custom.scss
- src/templates/home/home.html
Demande de John : 
- Avoir 2 lignes au lieu de 3 dans la section "notre action
- Dans la première colonne, mettre à la ligne le texte "par leurs porteurs".
> Page d'accueil modification de la section "notre action"

- src/backers/admin.py
https://trello.com/c/QyCaQQxj/1031-affichage-dinfos-sur-les-auteurs-des-aides-sur-les-fiches-porteurs-en-admin
Dans l'admin on affiche le nom de l'auteur de chaque aide sur la fiche de chaque porteur.
> Affichage des auteurs des aides sur la page backer admin

- src/locales/fr/LC_MESSAGES/django.po
- Avant de merger cette PR, il faudrait merger d'abord la PR sur l'email de confirmation de l'alerte.
- À tester plus particulièrement : la suggestion des projets
> Mise à jour des traductions

- src/aids/models.py
- src/aids/views.py
- src/static/css/_custom.scss
- src/templates/aids/detail.html
https://trello.com/c/mcLptabH/957-affichage-lien-texte-aides-entreprise-sur-fiche-aide
> Ajout d'un lien vers Aides-entreprises pour les aides destinées aux entreprises

- src/projects/admin.py
Ajoute la possibilité d'exporter les projets depuis l'admin v2
> Ajoute la possibilité d'exporter les projets V2

- src/static/css/_custom.scss
- src/templates/aids/detail.html
https://trello.com/c/G4QNgrEW/1065-d%C3%A9place-le-bloc-remarque-de-la-page-aide-detail
> Déplace le bloc 'remarque' de la page Aid-detail

- src/minisites/views.py
The ordering was not applied to minisites views
> Problème avec l'ordre des aides dans les PP

- src/search/views.py
- src/templates/search/step_category.html
https://trello.com/c/eSBNfRkt/1073-energie-d%C3%A9chets-%C3%A0-lancer-en-collecte-projet
Si la thématique "énergies / déchets" est sélectionnée par l'utilisateur dans le formulaire de recherche, l'étape suggestion de projets doit s'afficher.
> Possibilité de suggestion de projets pour la thématique "énergies-déchets"

- src/core/tests/test_utils.py
- src/static/js/aids/duplicate_buster.js
- src/static/js/carousel.js
> Obtenir l'info qu'une aide est doublonnée sans avoir à valider le contenu

- src/search/views.py
https://trello.com/c/EdjnmqTs/1092-ouverture-de-lacc%C3%A8s-%C3%A0-l%C3%A9tape-projets-pour-la-th%C3%A9matique-mobilit%C3%A9-transports
> Accès à l'étape projet depuis la thématique "mobilité-transports"

- src/static/css/_custom.scss
- src/static/css/_globals.scss
https://trello.com/c/XU7qTiQR/1111-probl%C3%A8me-affichage-bouton
> Fix style du bouton sauvegarde d'une aide en brouillon

- src/home/views.py
https://trello.com/c/LJnIwjsN/1110-comptabiliser-uniquement-les-financeurs-dans-les-stats-de-la-homepage
> Comptabiliser uniquement les financeurs pour les stats de la Homepage

- src/core/urls.py
- src/scalingo.json
https://trello.com/c/13Lahfmf/1129-proposer-une-redirection-des-url-aids-vers-aides
> Permet l'ouverture des pages avec l'url aids à la palce de aides

- README.md
@lazybird Je ne suis plus à jour sur ta procédure de livraison. Je te laisse compléter la PR avec les bonnes infos ?
> Vire les références à OVH du readme

- src/templates/search/step_project.html
https://trello.com/c/Fmnfa1d3/1177-impossible-de-passer-l%C3%A9tape-de-choix-de-projet
> Fix affichage lien de navigation à l'étape de recherche projets

- src/locales/fr/LC_MESSAGES/django.po
- src/search/forms.py
https://trello.com/c/kzzWhXYz/1143-changement-dintitul%C3%A9-dans-parcours-de-recherche-interco
> Remplace "Intercommunalité" par "Intercommunalité / Pays"

- src/static/css/_globals.scss
- src/templates/aids/detail.html
https://trello.com/c/zdUGLuu2/1171-revu-du-fil-dariane-sur-les-fiches-aides
> Redesign du fil d'ariane

- src/aids/models.py
- src/static/css/_custom.scss
- src/templates/aids/_aid_result.html
https://trello.com/c/hVf2Jiqq/1169-afficher-les-aides-qui-souvrent-prochainement
> Mention de l'ouverture prochaine de l'aide sur la carte de l'aide

- src/static/css/_custom.scss
https://trello.com/c/IXCDjLpo/1193-affichage-des-logos-pages-porteurs
> Bug : affichage logo sur la page porteur

- src/projects/factories.py
- src/stats/api/serializers.py
- src/stats/api/views.py
- src/stats/models.py
- src/stats/tests/test_api.py
Quelques améliorations : 
- généraliser le cleaning du champ `querystring` avant de sauvegarder
- rajoute des tests pour `AidMatchProjectEvent` et `AidEligibilityTestEvent`
> Améliorations sur le stockage des événements

- src/templates/minisites/_css.html
https://trello.com/c/74LKjycE/1212-ajustement-des-code-couleur-des-pp
https://trello.com/c/iJ4mTf1j/1211-probl%C3%A9me-affichage-barres-sur-les-fiches-aides
Fix la couleur de certains textes et/ou liens sur les PP
Fix le soulignement des titres sur la page de détail des aides
> Fix design PP

- src/projects/admin.py
- src/projects/resources.py
https://trello.com/c/Lkc8t700/1202-importer-les-projets-depuis-un-fichier-csv
> Importer des projets depuis un fichier csv

- src/static/css/_custom.scss
https://trello.com/c/A8xSgx5f/1219-espacement-sur-page-de-r%C3%A9sultats-sur-mobile
> Fix affichage de la page de résultats sur mobile

- src/locales/fr/LC_MESSAGES/django.po
https://trello.com/c/bb9XFf83/1252-ajout-dune-traduction-manquante-sur-les-pp
> Ajout d'une traduction manquante sur les PP

- src/Pipfile
- src/Pipfile.lock
- src/aids/admin.py
Temp fix en attendant une nouvelle version de https://github.com/farhan0581/django-admin-autocomplete-filter/
> Probléme de recherche en autocomplétion des périmètres dans l'admin

- src/locales/fr/LC_MESSAGES/django.po
https://trello.com/c/lIfVzfp4/1226-changement-de-texte-cr%C3%A9ation-dalerte
> Modification de la traduction des types d'aides dans le récapitulatif des filtres d'alertes

- src/static/css/theming.css
Je profite de cette PR pour : 
- fixer les couleurs de l'admin
- augmenter la width du champ porteur dans les PP depuis le ficher theming.css
> Fix design django-admin

- src/dataproviders/tests/test_utils.py
- src/dataproviders/utils.py
Pour réutiliser ensuite dans https://github.com/MTES-MCT/aides-territoires/pull/647 et https://github.com/MTES-MCT/aides-territoires/pull/644
> Import API : extraire la méthode de mapping des sous-thématiques

- src/minisites/views.py
Now comparing the incoming host with the canonical URL
> Modifier la manière de faire les redirections des PP

- src/minisites/views.py
> Modifier la manière de faire la redirection des PP - check canonical_url

- src/templates/aids/_promotions.html
- src/templates/aids/_results.html
https://trello.com/c/4ZnKzC9z/1292-affichage-des-interstices-promotionnels-m%C3%AAme-sil-y-a-moins-de-6-r%C3%A9sultats
> Affichage des interstices promotionnels même s'il y a moins de 6 résultats.

- src/dataproviders/utils.py
- src/static/css/_globals.scss
- src/static/js/responsive_iframe.js
- src/templates/aids/detail.html
- src/templates/backers/detail.html
- src/templates/blog/post_detail.html
- src/templates/minisites/_css.html
- src/templates/minisites/page_detail.html
- src/templates/pages/detail.html
- src/templates/search/search_page.html
https://trello.com/c/pwKkWHXk/1276-permettre-dajouter-des-vid%C3%A9os-embed-sur-les-pp
> Possibilité d'ajouter une iframe depuis le RichTextEditor

- src/dataproviders/management/commands/base.py
- src/dataproviders/management/commands/import_grand_est_api.py
- src/dataproviders/management/commands/import_nouvelle_aquitaine_rss.py
- src/dataproviders/management/commands/import_pays_de_la_loire.py
- fix sur les `ADMIN_ID` manquants
- log le résultats des imports
> Import API : logger les stats d'import

- ONBOARDING.md
- src/stats/utils.py
Mise à jour de la commande psql pour la gestion de french_unaccent
> Mise à jour de l'onboarding

- src/templates/minisites/_footer.html
- src/templates/minisites/_header.html
https://trello.com/c/KFc0U9wu/1289-pp-ouverture-lien-en-url-externe
> ouverture des liens externes des partenaires dans un nouvel onglet sur les PP

- src/static/css/theming.css
https://trello.com/c/6r65UZzU/1287-am%C3%A9lioration-dinterface-du-module-d%C3%A9dition-de-texte
> Améliore la prévisualisation de l'éditeur trumbowyg

- src/aids/forms.py
- src/minisites/views.py
https://trello.com/c/mc7RZVtu/1253-prise-en-compte-du-crit%C3%A9re-de-tri-dans-la-query-de-la-pp
> Prise en compte du filtre de tri dans la querystring de base des PP

- src/aids/api/urls.py
- src/aids/api/views.py
- src/aids/constants.py
- src/aids/models.py
> API : ajout d'un endpoint pour lister tous les bénéficiaires

- src/aids/api/urls.py
- src/aids/api/views.py
> API : ajout d'un endpoint pour lister tous les etats d'avancements

- src/aids/api/urls.py
- src/aids/api/views.py
- src/aids/forms.py
- src/aids/models.py
- src/dataproviders/management/commands/import_bpi.py
- src/dataproviders/management/commands/import_grand_est_api.py
- src/dataproviders/management/commands/import_loire_bretagne.py
- src/dataproviders/management/commands/import_pays_de_la_loire.py
> API : ajout d'un endpoint pour lister toutes les recurrences

- src/aids/api/urls.py
- src/aids/api/views.py
> API : ajout d'un endpoint pour lister tous les types de dépenses

- src/backers/views.py
- src/categories/api/serializers.py
- src/categories/api/urls.py
- src/categories/api/views.py
- src/core/urls.py
avec les sous-thématiques encapsulées
> API : Ajout d'un endpoint pour lister les thématiques

- src/aids/api/doc.py
- src/aids/api/serializers.py
- src/aids/api/urls.py
- src/aids/api/views.py
- src/backers/api/doc.py
- src/backers/api/views.py
- src/categories/api/views.py
- src/eligibility/api/views.py
- src/geofr/api/doc.py
- src/geofr/api/serializers.py
- src/geofr/api/urls.py
- src/geofr/api/views.py
- src/programs/api/views.py
- src/stats/api/views.py
- Choices : 
- key/value --> id/name
- ajout de serializers
- Documenter les paramètres possibles
- Cleanup
> API : refactoring & documentation

- src/static/css/_custom.scss
- src/templates/home/home.html
- src/templates/search/step_audience.html
- src/templates/search/step_category.html
- src/templates/search/step_perimeter.html
- src/templates/search/step_theme.html
Réalignement des éléments du bloc how en version mobile/pad
> Fix responsive du bloc how sur la page home

- src/blog/views.py
https://trello.com/c/JI4ismPK/1380-196-pr%C3%A9visualiser-un-article-de-blog
> Prévisualisation des articles de blog en brouillon pour les super-utilisateurs

- src/templates/_header.html
https://trello.com/c/I6l9UFtS/1392-acc%C3%A9der-au-portefeuille-daides-en-cliquant-sur-lic%C3%B4ne-utilisateur-dans-la-barre-de-menu
> Accéder au portefeuille d'aides en cliquant sur l'icône utilisateur dans la barre de menu

- src/aids/admin.py
https://trello.com/c/mA8EfAeQ/1394-204-rapprocher-les-champs-porteurs-instructeurs-sugg%C3%A9r%C3%A9s-et-porteurs-instructeurs-dans-lapp-aide-de-ladmin
> Rapprocher les champs "porteurs/instructeurs suggérés" et "porteurs/instructeurs" dans l'app aid de l'admin

- src/aids/views.py
- src/static/css/_custom.scss
- src/templates/aids/edit.html
https://trello.com/c/JHW76ij0/1339-169-211-mettre-les-ast%C3%A9risques-sur-les-champs-obligatoires-du-formulaire-de-contribution
> Indiquer les champs obligatoires du formulaire de contribution d'aides

- src/locales/fr/LC_MESSAGES/django.po
- src/templates/_header.html
https://trello.com/c/4cgYQqoa/1307-ajouter-un-onglet-blog-dans-la-barre-de-navigation
> Ajouter un onglet "blog" dans la barre de navigation

- src/templates/accounts/_sidebar_menu.html
- src/templates/accounts/user_alert_dashboard.html
- src/templates/aids/draft_list.html
- src/templates/projects/project_detail.html
- src/templates/projects/projects_list.html
- src/templates/projects/update_project.html
https://trello.com/c/Gy84AUTb/1417-changer-lordre-du-menu-du-compte-mettre-dabord-diffuser-mes-aides-puis-g%C3%A9rer-mes-projets
https://trello.com/c/UA6ypig9/1419-fil-dariane-%C3%A0-modifier
> Amélioration du fil d'ariane pour le compte utilisateur

- src/accounts/views.py
- src/templates/accounts/user_dashboard.html
https://trello.com/c/C5pHzNGp/1425-am%C3%A9lioration-page-tableau-de-bord
> Ajout du nombre de projets, aides et collaborateurs de l'utilisateur sur la page tableau de bord

- src/templates/aids/detail.html
https://www.notion.so/Supprimer-l-encart-Am-liorer-cette-aide-ef549dd36abd4560a1b38dbae7d1875e
> Fiche Aide : Suppression du CTA "améliorer cette aide"

- src/organizations/admin.py
https://trello.com/c/uLdlnLeh/1430-am%C3%A9lioration-admin-ajout-de-filtre-pour-les-structures
> Amélioration admin : ajout d'un filtre "type d'organization" pour les structures

- src/projects/admin.py
https://trello.com/c/PFhwHxey/1431-am%C3%A9lioration-admin-ajout-des-champ-aides-associ%C3%A9es-et-nombres-daides-associ%C3%A9es-pour-les-projets
> Amélioration admin : ajout des champ "aides associées" et "nombres d"aides associées" pour les projets

- src/templates/accounts/_sidebar_menu.html
https://www.notion.so/Pouvoir-acc-der-l-admin-d-AT-depuis-le-Compte-Utilisateur-8f61969472e64fa4b701e79daa156040
> Compte utilisateur : Ajout d'un lien vers l'espace admin pour les super-utilisateurs

- src/templates/minisites/_css.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=01558c819798499d982e143557596c42
> Portails : Fix le cas où toutes les couleurs du portail n'ont pas été renseignées dans l'admin

- src/static/css/_custom.scss
- src/templates/blog/post_detail.html
https://www.notion.so/Article-de-blog-fix-responsive-367cf741d5ab44e28908fa0625892945
> Blog : améliore le responsive pour les images ajoutées depuis l'éditeur de texte

- src/templates/alerts/_alert_modal.html
https://www.notion.so/Wording-changer-sur-la-popup-Alerte-a63b82f160b6414ab4705fc186e322b4
> Fix le texte de la modal "création d'une alerte"

- src/templates/accounts/_help_collaborators_modal.html
- src/templates/accounts/_sidebar_menu.html
- src/templates/accounts/collaborators.html
https://www.notion.so/Expliquer-quoi-ca-sert-d-ajouter-un-collaborateur-5983d2d0653948c38141e88c4df48c0f
> Ajouter une modale "aide infos" pour la page "collaborateurs"

- src/accounts/forms.py
- src/accounts/views.py
- src/templates/accounts/register.html
https://www.notion.so/Rendre-le-champ-type-de-structure-obligatoire-lors-de-l-inscription-9d9ef35d6d17488583243df5774b6514
> Rendre le champ "type de structure" obligatoire lors de l'inscription

- src/templates/accounts/_sidebar_menu.html
- src/templates/accounts/user_alert_dashboard.html
https://www.notion.so/Rendre-plus-visible-l-onglet-Mes-alertes-dans-le-menu-utilisateur-2aec70eccc114cce9344e3ccfa6e6914
> Compte utilisateur : Rendre plus visible l'onglet "Mes alertes" dans le menu

- src/aids/admin.py
https://www.notion.so/Dans-l-admin-pouvoir-retrouver-des-aides-partir-du-champ-Nom-initial-34752b58e93641a59f2741fc691712af
> Admin: pouvoir retrouver des aides à partir du champ "Nom initial"

- src/templates/accounts/login.html
- src/templates/accounts/register.html
- src/templates/backers/detail.html
- src/templates/home/contact.html
- src/templates/minisites/page_detail.html
- src/templates/pages/detail.html
https://www.notion.so/Ajout-des-balises-OG-manquantes-ae079e3010084fc5ac6000d424b587b4
> Amélioration des balises OG pour les pages créées depuis l'admin

- src/organizations/forms.py
- src/organizations/views.py
- src/search/views.py
- src/static/css/_custom.scss
- src/static/js/aids/perimeter_autocomplete.js
- src/templates/_field_snippet.html
- src/templates/organizations/create.html
- src/templates/organizations/update.html
- src/templates/search/general_search.html
https://www.notion.so/Recherche-en-fonction-du-p-rim-tre-et-du-type-de-structure-de-l-utilisateur-connect-sur-la-page-tr-eb29eecee804416fa3d850fadbf7c7e3
> Trouver des aides : pré-remplir les champs "périmètre" et "bénéficaire" si l'utilisateur est connecté

- src/templates/search/general_search.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=4c5725067af946919e30b83d32fa1a55
> Pouvoir déselectionner la structure choisie dans le select de la page "trouver des aides"

- src/accounts/views.py
- src/aids/views.py
- src/templates/aids/detail.html
- src/templates/projects/_match_aid_modal.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=1a4269b0ab0548cd84f0067c7fa2af82
> Rediriger l'utilisateur vers la page de détail d'une aide après sa connexion s'il était sur cette page auparavant

- src/alerts/views.py
- src/templates/alerts/_alert_modal.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=4ffd3e756df548f6b57483ab5d9c63e3
> Alerte email : si l'utilisateur est connecté confirmé automatiquement l'alerte

- src/templates/aids/detail.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=85b9ed9a5ad543a39f8d459926ec05bf
> Modification de la mention spécifique aux aides de la Région Ile-de-France

- src/projects/views.py
- src/templates/_pagination.html
- src/templates/projects/projects_list.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=d6209997152f4f65bc8d29f729464d8a
> Ajout d'une pagination pour la page projects-list

- src/aids/forms.py
- src/static/css/_custom.scss
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=087d5f9f126e44479ac613260bf53706
> Formulaire édition d'une aide : rendre le champ bénéficiaire obligatoire

- src/static/css/_globals.scss
- src/static/js/aids/display_results_list.js
- src/templates/aids/_aid_result_as_list.html
- src/templates/aids/_base_search.html
- src/templates/aids/_results.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=6fe37a971d8a4c4a937b626bde6d4049
> Affichage de la liste d'aides en tableau ou en carte

- src/templates/accounts/complete_profile.html
- src/templates/accounts/contributor_profile.html
- src/templates/accounts/register.html
- src/templates/accounts/register_success.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=34a424b311a4479f872b0c147b9ea54e
> Amélioration du parcours d'inscription au compte utilisateur

- src/aids/forms.py
- src/templates/search/general_search.html
https://www.notion.so/G-rer-le-OU-dans-le-moteur-de-recherche-ed23c733ff0c427f83e38fbf9166a0a6
> Gérer le "OU" dans la recherche textuelle

- src/aids/views.py
- src/templates/projects/_delete_aid_modal.html
- src/templates/projects/project_detail.html
- src/templates/projects/projects_list.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=72b2d3f097384393abebcb164c18e94b
> Demander une confirmation à la suppression du lien entre une aide et un projet

- src/templates/_header.html
https://www.notion.so/Ajouter-un-bandeau-de-communication-dans-le-header-0c1a3fa19c0d4e51bb964484484cfea0
> Ajouter un bandeau de communication dans le header

- src/templates/home/legal_mentions.html
https://www.notion.so/Mentions-l-gales-915aa92f4dee4c848343b1ac0e174b9b
> Mise à jour des mentions légales

- src/templates/home/legal_mentions.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=fc21f5c7952e4358bcd8c28b8babe6ba
> Mise à jour des CGU

- src/accounts/templatetags/accounts.py
- src/organizations/templatetags/organizations.py
- src/static/css/_globals.scss
- src/stats/templatetags/stats.py
- src/stats/urls.py
- src/stats/views.py
- src/templates/stats/dashboard.html
- src/templates/stats/organizations_stats.html
- src/templates/stats/projects_stats.html
- src/templates/stats/users_stats.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=f83531de083a478a9d70a9edf7a81162
> Création des pages stats comptes utilisateurs, structures et projets

- src/stats/forms.py
- src/stats/views.py
- src/templates/stats/dashboard.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=5e64d397ef19432d9cbd2b0e684af207
> Amélioration du dashboard de stats

- src/home/forms.py
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=269168e985844f40bcffd86022fa61e0
> Mise à jour des choix de sujet du formulaire de contact

- src/templates/accounts/collaborators.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=05aca12efe6f43d2a23869988e765991
> Afficher le statut de l'invitation à collaborer

- src/accounts/forms.py
- src/accounts/views.py
- src/templates/emails/invite_login_token.txt
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=dbf00b9f17ea45db83a2634c91e5234c
> Améliorer l'inscription des collaborateurs

- src/accounts/urls.py
- src/accounts/views.py
- src/templates/accounts/_delete_history_login_modal.html
- src/templates/accounts/_sidebar_menu.html
- src/templates/accounts/history_login.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=14242ad2bef34c54bbfeec94c37ff7c5
> Création d'une page historique de connexion

- src/organizations/constants.py
- src/organizations/forms.py
- src/templates/organizations/update.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=3784856b592a492d8ab457ec40f603d4
> Possibilité pour l'utilisateur de mettre à jour le type de sa structure

- src/alerts/forms.py
- src/alerts/urls.py
- src/alerts/views.py
- src/templates/accounts/user_alert_dashboard.html
- src/templates/alerts/_delete_alert_modal.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=86d552aadc174f67b12a6f226d81e74a
> Confirmation de la suppression d'une alerte depuis le compte utilisateur dans une modale

- src/templates/alerts/alert_body.html
- src/templates/alerts/alert_body.txt
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=38e1ed6cdcc34294a1522ac8c01f76ea
> Alert : Enlever la possibilité de noter les alertes dans l'email d'alerte

- src/static/css/_globals.scss
- src/templates/aids/detail.html
https://www.notion.so/Am-lioration-du-bouton-Poursuivre-la-d-marche-pour-obtenir-l-aide-009c2b0f7f174c80b8cbd36709ffcea0
> Améliorer la visibilité du bouton-accordéon sur la page détail des aides

- src/accounts/forms.py
- src/aids/constants.py
- src/dataproviders/data/grand_est_api_audiences_mapping.csv
- src/dataproviders/data/nouvelle_aquitaine_rss_audiences_mapping.csv
- src/dataproviders/data/pays_de_la_loire_audiences_mapping.csv
- src/dataproviders/data/plan_france_relance_audiences_mapping.csv
- src/organizations/constants.py
https://www.notion.so/Harmoniser-les-termes-d-intercommunalit-sur-l-ensemble-du-site-remplacer-EPCI-0ae0b79e2f8a41888b4468ab9cda261a
> Remplacer la constante "EPCI à fiscalité propre" par "Intercommunalité / Pays"

- src/templates/_base.html
- src/templates/minisites/search_page.html
https://www.notion.so/Enlever-le-dark-mode-sur-les-portails-dfd5668d1c0846a7904f297d54b62e6a
> Portails : le theme clair est le thème imposé au système

- src/aids/forms.py
- src/aids/migrations/0152_add_categories_to_search_vector_unaccented.py
- src/aids/models.py
- src/dataproviders/management/commands/base.py
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=ced8ee2d75654c7eac0b394688176a87
> Recherche textuelle : prise en compte des sous-thématiques dans le search-vector

- src/aids/resources.py
[…-import-export update](https://www.notion.so/R-parer-la-fonction-d-import-des-aides-depuis-l-admin-3961da3d5bc04390a0027413a7a5feb2)
> Répare la fonction d’import des aides depuis l’admin

- src/accounts/tests/test_views.py
- src/accounts/urls.py
- src/core/tests/test_utils.py
- src/core/urls.py
- src/locales/fr/LC_MESSAGES/django.po
- src/pytest.ini
- src/templates/_form_header.html
- src/templates/accounts/login_error.html
Fait pour les apps core et accounts. Reste l'app aids.
https://www.notion.so/Correction-des-tests-unitaires-qui-ne-passent-plus-d7a4e81cf1064df5bd2b89b3d589ee6e
> Réparation des tests unitaires cassés

- src/accounts/admin.py
- src/accounts/models.py
- src/accounts/resources.py
https://www.notion.so/Pouvoir-extraire-la-base-de-nos-utilisateurs-b-nef-et-porteurs-avec-toutes-les-infos-f750d6655ac9400f9d8cb0fc63f087d0
> Exporter les contributeurs et bénéficiaires

- src/organizations/templatetags/organizations.py
Solution minimale au bug décrit à la page : https://www.notion.so/Plantage-sur-la-page-Statistiques-Structures-du-dashboard-7b38bf5de8224756980c5505503d8727
> Plantage sur la page Statistiques Structures du dashboard

- src/core/settings/base.py
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=df29a985a4f842cebc5aa7fdd77cb2f5
> Redirige france-relance-guyane vers le portail guyane

- src/organizations/resources.py
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=41b8b1777d6c459392a250661e6d1570
> Ajout du nombre de projets dans l'export des structures

- src/templates/accounts/_info_alert_modal.html
- src/templates/accounts/user_alert_dashboard.html
https://www.notion.so/Mettre-un-bouton-information-c-t-du-titre-Mes-alertes-de3a1b7a6c954008ada4fc3e89545304
> Ajout d'un bouton 'aide' sur la page "mes alertes" du compte utilisateur

- src/aids/migrations/0156_search_vector_fields_range.py
- src/aids/models.py
https://www.notion.so/Am-liorer-la-pertinence-du-moteur-de-recherche-textuelle-1bf5d0a8b1c942139492b30156e6b80b
> Mise à jour de l'index du search_vector pour les aides

- src/templates/accounts/register.html
https://www.notion.so/Changer-l-option-par-d-faut-au-moment-de-l-inscription-pour-les-communes-472d08b39bd44eaf867b557e050dabdb
> Ajoute une option vide par défaut au select du champ beneficiary_function dans le formulaire d'inscription

- src/projects/views.py
- src/static/css/_globals.scss
- src/templates/projects/_project_search_aid_modal.html
- src/templates/projects/projects_list.html
https://www.notion.so/Proposer-directement-la-recherche-d-aides-apr-s-la-cr-ation-d-un-projet-99636f139d044c698ef6ab44fb9d1434
> Proposer directement la recherche d’aides après la création d’un projet

- src/stats/views.py
- src/templates/stats/dashboard.html
- src/templates/stats/organizations_stats.html
… of orgs and accurate number of perimeters for each scale
> Déduplication des organisations sur l’accueil du dashboard

- src/Pipfile
- src/Pipfile.lock
> Mise à jour du paquet django-dsfr

- src/aids/views.py
- src/templates/aids/detail.html
https://www.notion.so/Surligner-les-mots-cl-s-recherch-s-dans-les-pages-d-tails-des-aides-4915cc7c890f4edbb4256c56807ea965
> Surligner les mots clés recherchés dans les pages détail des aides

- src/templates/projects/_project_search_aid_modal.html
https://www.notion.so/Dans-le-compte-utilisateur-Votre-projet-a-bien-t-cr-Nous-avons-trouv-1-aides-qui-pourrai-749859437a8d440eaa54d854efb80c45
> Ajout d'une expression conditionnelle au singulier pour la modal "project_search_aid"

- src/aids/views.py
- src/templates/aids/detail.html
[Classer les mots-clés par ordre alphabétique](https://www.notion.so/Classer-les-mots-cl-s-par-ordre-alphab-tique-e044e4608b42445198e3569134e1a8ad)
> Afficher les tags sous-thématiques et mots-clés par ordre alphabéthique

- src/organizations/views.py
- src/projects/urls.py
- src/projects/views.py
- src/templates/projects/project_detail.html
https://www.notion.so/V-rification-de-l-identit-de-l-utilisateur-avant-acc-s-aux-pages-de-mise-jour-de-la-structure-et--4ee6b598c3394432bd73d29ad691460c
> Révise l'accès aux organisations et projets

- src/pages/admin.py
Correction du style qui contrariait le linter.
> Correction Checkstyle

- src/dataproviders/management/commands/import_welcome_europe.py
- src/templates/aids/detail.html
https://www.notion.so/Supprimer-la-mention-vous-recherchez-des-aides-pour-les-entreprises-f72dc1f10f2a4c9bb9eb2b3eeeef779b
ET
https://www.notion.so/Rendre-visible-la-date-de-publication-mise-a-jour-de-la-fiche-d-aide-138e47315c214f148e57aa14ecc53d15
> Supprimer la mention “vous recherchez des aides pour les entreprises”

- src/aids/forms.py
- src/aids/migrations/0161_add_programs_to_search_vector.py
- src/aids/models.py
- src/dataproviders/management/commands/base.py
https://www.notion.so/Ajouter-le-champ-programme-dans-les-champs-v-rifi-s-par-la-recherche-textuelle-6fadbead83984eeeb945166f2f453668
> Ajouter le champ “programme” dans les champs vérifiés par la recherche textuelle 

- src/aids/forms.py
- src/aids/tests/conftest.py
https://www.notion.so/Emp-cher-la-publication-de-l-aide-si-les-champs-obligatoires-ne-sont-pas-remplis-009702322ed34b12937cb0aa6eedc0d6
> Empêcher la publication de l’aide depuis l'admin si les champs obligatoires ne sont pas remplis

- src/accounts/tests/test_invite_collaborator.py
- src/accounts/tests/test_roles.py
- src/accounts/tests/test_views.py
- src/dataproviders/tests/test_import_commands.py
https://www.notion.so/Attribuer-une-adresse-email-tous-les-comptes-de-test-9a8fcd23c2dc46be99af66f613e0be29
> Attribuer une adresse email à tous les comptes de test

- src/Pipfile
- src/Pipfile.lock
- src/geofr/services/validators.py
https://www.notion.so/Ajouter-des-v-rificateurs-pour-les-SIREN-SIRET-et-APE-aa9bcbfab23c41bd927351930790f15e
> Ajouter des vérificateurs pour les SIREN, SIRET et APE

- src/accounts/tasks.py
- src/templates/emails/accept_invitation.txt
- src/templates/emails/invite_existent_user.txt
- src/templates/emails/leave_organization.txt
https://www.notion.so/Am-lioration-des-emails-de-fusion-des-organisations-3ec1c674fa5c40d899758acfa144170a
> Amélioration des emails de fusion des organisations

- src/templates/accounts/register.html
https://www.notion.so/Simplification-de-l-inscription-suppression-de-la-division-en-2-tapes-953c9e9c44b4467786603f95cb09bc8c
> Formulaire d'inscription : inversion de la position des champs organization_name et organization_type

- src/projects/admin.py
- src/projects/apps.py
- src/projects/factories.py
- src/projects/fields.py
- src/projects/migrations/0001_initial.py
- src/projects/migrations/0002_project_status.py
- src/projects/migrations/0003_auto_20210318_1456.py
- src/projects/migrations/0004_project_key_words.py
- src/projects/migrations/0005_auto_20210430_1323.py
- src/projects/migrations/0006_project_remove_unused_fields.py
- src/projects/migrations/0007_project_due_date.py
- src/projects/migrations/0008_project_organizations.py
- src/projects/migrations/0009_project_author.py
- src/projects/migrations/0010_alter_project_due_date.py
- src/projects/migrations/0011_translate_verbose_name.py
- src/projects/resources.py
- src/projects/tasks.py
- src/projects/urls.py
Passage de black sur l'app projects
> black on projects

- src/Pipfile.lock
- src/aids/views.py
- src/alerts/views.py
- src/dataproviders/tests/test_utils.py
- src/dataproviders/utils.py
- src/locales/fr/LC_MESSAGES/django.po
- src/templates/_base_pdf.html
- src/templates/_footer.html
- src/templates/accounts/register.html
- src/templates/accounts/user_alert_dashboard.html
- src/templates/accounts/user_api_token.html
- src/templates/accounts/user_delete_dashboard.html
- src/templates/admin/admin_lite/change_form.html
- src/templates/aids/_share_modal.html
- src/templates/aids/detail.html
- src/templates/aids/draft_list.html
- src/templates/aids/edit.html
- src/templates/alerts/_alert_modal.html
- src/templates/home/_mailing_list_form.html
- src/templates/home/accessibility.html
- src/templates/home/contact.html
- src/templates/home/legal_mentions.html
- src/templates/home/privacy_policy.html
- src/templates/minisites/_footer.html
- src/templates/minisites/_header.html
- src/templates/projects/project_detail.html
- src/templates/projects/project_export_pdf.html
https://www.notion.so/Accessibilit-revoir-les-liens-externes-43a00e872ee14f27b316038575013e12
> Accessibilité - revoir les liens externes

- src/templates/aids/_aid_result.html
- src/templates/aids/detail.html
- src/templates/blog/post_detail.html
Corrections d'accessibilités suite au point sur les contenus rédactionnels :
- emoji UE 🇪🇺
- Retrait du nom des auteurs du blog du alt text de leur photo
> Corrections d'accessibilité mineures

- src/aids/forms.py
https://www.notion.so/Portails-Changer-le-nom-du-filtre-La-structure-par-Le-b-n-ficiaire-7ed54534eb48466e8969bdafc312856e
> Renomme le label du champ "targeted-audiences" sur le cartouche des portails

- src/accounts/admin.py
- src/accounts/resources.py
- src/exporting/tasks.py
https://www.notion.so/Extract-base-utilisateurs_champs-ajouter-types-d-organisation-et-code-postale-de-la-structure-e33ea978df4647038dd54d3875e620f3
+ possibilité d'export en tâche de fond
> Ajout des champs "type d'organisation" et "code postal de l'organisation" à l'export utilisateurs

- src/accounts/forms.py
- src/alerts/tests/test_views.py
- src/locales/fr/LC_MESSAGES/django.po
- src/templates/alerts/_alert_modal.html
https://www.notion.so/R-server-la-cr-ation-d-alertes-aux-utilisateurs-connect-s-f07c4fc9d2a841d9aa4f50d7d8afb193
> Réserver la création d’alertes aux utilisateurs connectés 

- src/dataproviders/data/ile_de_france_audiences_mapping.csv
- src/dataproviders/data/ile_de_france_categories_mapping.csv
- src/dataproviders/management/commands/import_ile_de_france.py
https://www.notion.so/Int-gration-flux-Conseil-R-gional-d-Ile-de-France-90f98cd2f40f4d2da5e2111ac90d5ab1
> Import Conseil Régional d'Ile de France : création d'une commande d'import 

- src/Pipfile
- src/Pipfile.lock
- src/accounts/tests/test_invite_collaborator.py
- src/accounts/views.py
- src/core/context_processors.py
- src/core/settings/base.py
- src/static/js/eligibility/eligibility_test_form.js
- src/templates/_base.html
- src/templates/admin/base_site.html
- src/templates/aids/_share_modal.html
- src/templates/home/privacy_policy.html
- src/templates/minisites/_css.html
- src/templates/rest_framework/api.html
https://www.notion.so/Mettre-en-place-des-content-security-policies-ec57f218fe6d40b09c1f83c7c2e3a96d
> Mettre en place des content security policies

- src/static/js/projects/project_types_autocomplete.js
- src/templates/accounts/_sidebar_menu.html
- src/templates/projects/favorite_or_public_project_aids_list.html
- src/templates/projects/favorite_project_detail.html
- src/templates/projects/favorite_projects_list.html
https://www.notion.so/Ouverture-des-projets-Step-2-1-1169fdedfa0649049020674065dac344
> Ouverture des projets : 2.1

- src/accounts/resources.py
https://www.notion.so/Ajouter-le-champs-nombre-de-projets-de-la-structure-l-extract-user-1768fcd0530f48daad836ae585d85c45
> Ajouter le nombre de projets de chaque organisation à l'export utilisateur

- src/core/settings/base.py
- src/minisites/views.py
- src/static/css/_globals.scss
- src/templates/minisites/stats.html
https://www.notion.so/Cr-er-une-page-statistiques-pour-France-Mobilit-s-34b765fd057644c3ae73ec962c63933d
> Page "statistiques" spécifique pour France-mobilités

- src/accounts/resources.py
https://www.notion.so/Ajouter-le-champs-nombre-d-aides-sauvegard-es-dans-l-extract-user-3a0bba832e044eb8a2edea26d14e0d4b
> Ajout d'un champ "Présence d'aides d'associées à un projet" dans l'extract user

- src/templates/stats/dashboard_acquisition.html
- src/templates/stats/dashboard_base.html
- src/templates/stats/dashboard_consultation.html
- src/templates/stats/dashboard_engagement.html
- src/templates/stats/dashboard_porteurs.html
Nécessaire pour la nouvelle CSP.
> Ajout d’attributs `nonce` sur les scripts

- src/.pre-commit-config.yaml
PR liée à https://github.com/AICoE/aicoe-ci/issues/53
> Modifie la config des pre-commit hooks

- src/aids/admin.py
- src/aids/resources.py
- src/exporting/tasks.py
https://www.notion.so/Pouvoir-consulter-et-extraire-le-statut-des-aides-e4e36c47a28d4d96a99756775bef4f2f
> Amélioration de l'espace admin pour les objets aidproject

- src/aids/views.py
- src/templates/accounts/collaborators.html
- src/templates/accounts/user_alert_dashboard.html
- src/templates/aids/_base_search.html
https://www.notion.so/Accessibilit-Title-des-pages-c8d806c992364c3da617ffd62bd7bbdc
> Accessibilité - Title des pages

- src/home/views.py
- src/organizations/constants.py
- src/projects/forms.py
- src/projects/views.py
- src/static/css/_custom.scss
- src/static/css/_select2-dsfr.scss
- src/static/css/_select2.scss
- src/static/js/projects/search_project_form_advanced.js
- src/templates/home/home.html
- src/templates/projects/_project_search_form.html
- src/templates/projects/public_projects_list.html
https://www.notion.so/Ouverture-des-projets-v3-Ajout-d-un-moteur-de-recherche-5a2bac3295124d7c80e0048867f70cb5
> Moteur de recherches pour les projets publics

- src/templates/aids/_warning_fonds_vert.html
https://www.notion.so/M-j-bandeau-Fonds-Vert-fcee2b3a7a9b40d9a58ca108d19383ec
> Mettre à jour le bandeau Fonds Vert 

- src/aids/views.py
- src/templates/aids/detail.html
https://www.notion.so/Bug-affichage-p-rim-tre-aides-IDF-207e325bad8a4f488383089de4276d74
> Fix : affichage du périmétre sur la fiche aide

- src/aids/forms.py
https://www.notion.so/R-soudre-le-bug-li-la-mise-jour-des-aides-c716ef24f1ba47cba37c620234764dd5
> Aide : mise à jour du champ "date-updated" depuis les éditeur front et back 

- src/Pipfile
- src/Pipfile.lock
- src/aids/views.py
- src/alerts/views.py
- src/core/__init__.py
- src/core/settings/base.py
- src/eligibility/admin.py
- src/projects/tests/test_views.py
- src/projects/views.py
- src/stats/views.py
- src/templates/minisites/_css.html
https://www.notion.so/Passer-de-Django-3-2-Django-4-1-e226a0cb60754ebca50cd2d35fe7cf97
> Passer de Django 3.2 à Django 4.1

- src/templates/_header.html
https://www.notion.so/Mettre-en-place-une-FAQ-41c0b79aeff146f08a075464994fb8f3
> Ajout d'un lien vers la FAQ général dans la barre de navigation

- src/Pipfile.lock
https://www.notion.so/R-soudre-l-alerte-de-s-curit-sur-la-d-pendance-future-01374c9fbd7748e6b54c6e99c20ca527
> Résoudre l'alerte de sécurité sur la dépendance future

- src/aids/admin.py
https://www.notion.so/Pouvoir-filtrer-les-aides-par-b-n-ficiaire-dans-l-admin-f430a92ee6774a8face25fa159eb0cf8
> Pouvoir filtrer les aides par bénéficiaire dans l’admin 

- src/templates/aids/_base_search.html
https://www.notion.so/Modifier-le-descriptif-de-la-barre-de-recherche-par-mots-clefs-d290c214d60e4c88814366d8155cd2ff
> Modifier le descriptif de la barre de recherche par mots clefs

- src/aids/tests/test_views.py
- src/templates/aids/detail.html
https://www.notion.so/Ajouter-un-bouton-Modifier-cette-aide-sur-la-page-de-d-tail-de-l-aide-1861204875074670ad0fafd0c72cdb7c
> Ajouter un bouton “Modifier cette aide” sur la page de détail de l’aide

- src/templates/programs/_faq_program.html
- src/templates/programs/detail.html
https://www.notion.so/Ajout-d-une-pr-cision-en-d-but-de-FAQ-fonds-vert-b449a0eace2043f38e78b6fe7ac6a321
> Ajout d'une précision textuelle pour la FAQ Fonds-vert

- src/templates/_header.html
https://www.notion.so/Ajouter-un-onglet-Programmes-d-aides-sur-le-site-qui-renverrait-vers-la-page-programmes-d89b6c46e67a4ee2baf7ef49788d6d21
> Ajout un lien vers la liste des programmes d'aides dans la barre de navigation principale

- src/geofr/services/counts_by_department.py
- src/templates/geofr/_backers_table.html
- src/templates/geofr/_programs_table.html
https://www.notion.so/Ajouter-le-type-d-aides-financi-res-CEE-dans-le-filtrage-sur-la-carto-1936a16a84f64d30a11133371ecc962b
> Ajouter le type d'aides 'CEE' dans le filtrage sur la cartographie des porteurs et programmes

- src/core/settings/base.py
- src/core/settings/test.py
- src/core/templatetags/settings.py
- src/core/tests/test_templatetags.py
- src/dataproviders/utils.py
- src/templates/home/_video.html
https://www.notion.so/Auto-h-bergement-des-vid-os-1206cae324dd42d09d64b4709d6586e1
> Auto-hébergement des vidéos

- src/Pipfile.lock
[…com/weblog/2023/feb/01/security-releases/](https://www.djangoproject.com/weblog/2023/feb/01/security-releases/)
> Update dependencies to fix security issue.

- src/accounts/factories.py
- src/accounts/tests/test_views.py
- src/accounts/urls.py
- src/accounts/views.py
- src/aids/models.py
- src/core/utils.py
- src/templates/accounts/register_success.html
https://www.notion.so/Bug-r-initialisation-du-mot-de-passe-357f6fa0f67945c191395f32fdb6e3a7
> Bug réinitialisation du mot de passe

- src/static/js/programs/tab_url_parameters.js
- src/templates/programs/detail.html
https://www.notion.so/Modification-automatique-de-l-url-de-la-page-programme-au-clic-sur-un-onglet-de-la-page-903b5f2a94a143ad80df6f1abf58e8fc
> Modification automatique de l’url de la page programme au clic sur un onglet de la page

- src/stats/views.py
https://www.notion.so/Doublons-dans-le-dashboard-fc909fb867084ff087dd8654baeeaf59
> Fix : clean du dashboard stats pour les structures importées

- src/aids/tests/test_search_engine.py
- src/aids/utils.py
https://www.notion.so/Ne-pas-faire-appara-tre-la-fiche-g-n-rique-nationale-si-la-d-clinaison-locale-qui-me-concerne-est-ex-8c991acda098468891bbbb73b11e3927
> Retirer l'aide générique des résultats si l'aide locale est clôturée

- src/programs/tests/test_views.py
Fix an issue where the random title or description would sometimes match the search filter
> Régler le problème avec les tests des programmes

- src/accounts/resources.py
https://www.notion.so/Ajouter-la-population-dans-l-export-des-utilisateurs-a97944f172a74a4eb10b763997156537
> Ajouter un champ population à l'export des utilisateurs

- src/home/forms.py
https://www.notion.so/Ajout-d-un-choix-J-ai-une-question-sur-le-fonds-vert-au-formulaire-de-contact-ab3c94fa0fb0490bb812aa68f15e77f5
> Ajout d'un choix spécifique au Fonds vert dans le formulaire de contact

- src/templates/projects/validated_projects_home.html
https://www.notion.so/Ajout-d-une-mention-d-information-b3d4669fa7954e11b19eade1964ed642?pvs=4
> Ajout d’une mention d’information

- src/accounts/views.py
- src/notifications/tasks.py
- src/notifications/urls.py
- src/templates/emails/unread_notifications.txt
https://www.notion.so/Revoir-le-courriel-de-notification-25ace8a28c654a4d81163c0f863c100c?pvs=4
> Revoir le courriel de notification

- src/projects/services/import_validated_projects.py
https://www.notion.so/Prendre-en-compte-les-d-partements-10-pour-l-import-des-projets-subventionn-s-8d359af897b4445eb5a14ad0476f3630?pvs=4
> Prendre en compte les départements < 10 pour l’import des projets subventionnés

- src/geofr/models.py
- src/programs/tests/test_views.py
- src/projects/forms.py
- src/projects/views.py
- src/scripts/start_web.sh
- src/templates/projects/validated_projects_results.html
https://www.notion.so/Bug-de-float-dans-le-calcul-des-distances-a6828130a63b4ea086ec0cb8ee3aa673?pvs=4
> Bug de float dans le calcul des distances

- src/templates/home/_video.html
https://www.notion.so/Pouvoir-demander-une-d-mo-facilement-depuis-le-site-3fcb928462d84f7191a6c60911ea7cd4?pvs=4
> Pouvoir demander une démo facilement depuis le site

- src/aids/views.py
- src/templates/projects/_match_aid_modal.html
- src/templates/projects/_suggest_aid_modal.html
…to reduce requests on aid-detail page
> Augmente les performances sur la page de Détail d'une aide

- src/dataproviders/management/commands/base.py
- src/dataproviders/management/commands/import_pays_de_la_loire.py
https://www.notion.so/Int-grer-le-flux-Pays-de-la-loire-988a9a38e9ce41c7abc6296d5bf314ae?pvs=4
> Mise à jour du flux Pays de la Loire

- src/templates/programs/_faq_program.html
https://www.notion.so/Ajout-d-un-accord-on-pour-les-rubriques-de-la-FAQ-Fonds-vert-66f31a8394c74a1a885a3b9aede65f61?pvs=4
> Ajout d’un accordéon pour les rubriques de la FAQ Fonds vert

- src/dataproviders/utils.py
- src/templates/home/_video.html
https://www.notion.so/Ne-pas-pr-charger-les-vid-os-ce551aafff174870933288f1b226b873?pvs=4
> Ne pas précharger les vidéos

- src/templates/robots.txt
https://www.notion.so/Am-liorer-le-robots-txt-da74de20ad83415c8d49ed6a34c808ad?pvs=4
> Améliorer le robots.txt

- src/templates/aids/_ds_modal.html
https://www.notion.so/Modification-du-texte-dans-la-modal-DS-4bbfe6a8ff684c289d918471372e2f42?pvs=4
> Modification du texte dans la modal DS

- src/projects/resources.py
https://www.notion.so/Am-liorations-du-fichier-des-projets-publics-et-priv-s-que-l-on-exporte-depuis-l-admin-59bd20156bed402c9bdaf09afd317dd8?pvs=4
> Ajout des champs 'is_public' et 'organization__code__perimeter' à l'export admin des projets publics

- src/aids/models.py
- src/templates/projects/favorite_or_public_project_aids_list.html
- src/templates/projects/project_detail.html
https://www.notion.so/Aides-sauvegard-es-dans-un-projet-ajouter-le-statut-r-ccurent-dans-la-colonne-ch-ance-aa97b65a689d49f98dbba89956e93144?pvs=4
> Ajouter le statut "récurrente" dans le tableau des aides liées à un projet

- src/projects/views.py
- src/templates/projects/_project_search_aid_modal.html
- src/templates/projects/project_detail.html
https://www.notion.so/Faire-passer-la-suggestion-auto-d-aides-du-titre-au-type-de-projet-lors-de-la-cr-ation-du-projet-dan-8555b82b6767424abc799d00a363d4d2?pvs=4
> Utiliser le champ 'project_types' pour la recherche d'aides à partir d'un projet

- src/templates/_base.html
https://www.notion.so/SEO-moteurs-de-recherche-remplacer-Aides-publiques-pour-les-collectivit-s-par-Aides-pour-les--6ca34f4e8354405585a19e8efed328cc?pvs=4
> Modification du 'title' et de la balise 'meta_description' du template 'base.html'

- src/aids/tests/test_search_engine.py
- src/conftest.py
- src/geofr/services/counts_by_department.py
- src/geofr/tests/test_views.py
https://www.notion.so/Bug-les-nombres-d-taill-s-d-aides-en-ing-nierie-sont-manquants-sur-la-cartographie-932987d9ca4541ecb404ae5ff3b6adf5?pvs=4
> Bug: les nombres détaillés d’aides en ingénierie sont manquants sur la cartographie

- src/exporting/tasks.py
- src/projects/admin.py
https://www.notion.so/Permettre-l-export-des-projets-en-t-che-de-fond-dda91eaf9fc149209eb8f6be8c589390?pvs=4
> Permettre l’export des projets en tâche de fond

- src/templates/401.html
- src/templates/404.html
- src/templates/_base.html
- src/templates/_form_header.html
- src/templates/accounts/complete_profile.html
- src/templates/accounts/join_organization.html
- src/templates/accounts/password_reset_confirm.html
- src/templates/accounts/user_api_token.html
- src/templates/accounts/user_dashboard.html
- src/templates/accounts/user_delete_dashboard.html
- src/templates/aids/_base_search.html
- src/templates/aids/_results.html
- src/templates/aids/draft_list.html
- src/templates/home/home.html
- src/templates/home/newsletter_confirm.html
- src/templates/home/newsletter_success.html
- src/templates/programs/_faq_program.html
- src/templates/projects/_create_or_update_project_form.html
- src/templates/projects/favorite_projects_list.html
- src/templates/projects/projects_list.html
- src/templates/projects/public_project_detail.html
- src/templates/projects/public_projects_list.html
- src/templates/projects/validated_projects_results.html
- src/templates/stats/dashboard_base.html
https://www.notion.so/Retirer-le-role-alert-du-code-de56c55fb97a423fb46c440f4a722586?pvs=4
> Retirer le role="alert" du code

- src/templates/aids/aids_export_pdf.html
https://www.notion.so/Faute-de-frappe-dans-l-export-des-aides-en-PDF-91835ef842f74c5eb80471bcf583a906?pvs=4
> Corriger le template d'exports des aides depuis le compte utilisateur

- src/aids/views.py
- src/templates/aids/detail.html
https://www.notion.so/Mettre-les-logos-des-instructeurs-sur-les-fiches-aides-95ac8ad6a06544539748e071852dee0a?pvs=4
> Ajouter les logos des instructeurs sur la page détail des aides

- src/Pipfile
- src/Pipfile.lock
- src/templates/_footer.html
[https://www.notion.so/Mise-jour-du-design-system-en-version-1-9-2-53f9a8e3d2a9448cac14d3d9794e89f2?pvs=4](https://github.com/MTES-MCT/aides-territoires/pull/1311)
>  Mise à jour du design system en version 1.9.2

- src/package-lock.json
- src/package.json
Pour résoudre le bug présent sur la PR #1310 de dépendabot
https://www.notion.so/Mise-jour-des-d-pendances-npm-bfbedfc993dc4475b5af74006982f101?pvs=4
> Mise à jour des paquets npm

- src/geofr/management/commands/import_communes_accounting_data.py
- src/geofr/services/import_data_from_ofgl.py
https://www.notion.so/Corriger-le-champ-display_order-sur-l-import-des-donn-es-financi-res-des-communes-1716aff3553d4a75916735aff9c042a6?pvs=4
> Corriger le champ display_order sur l'import des données financières des communes

- src/dataproviders/management/commands/import_pays_de_la_loire.py
https://www.notion.so/Int-grer-le-flux-Pays-de-la-Loire-988a9a38e9ce41c7abc6296d5bf314ae?pvs=4
> Amélioration du flux Pays de la Loire

- src/aids/urls.py
- src/aids/views.py
- src/templates/aids/detail_stats.html
- src/templates/aids/draft_list.html
https://www.notion.so/Enrichir-le-portefeuille-porteurs-de-statistiques-752f00c05db14bae985cf6e730d61b42?pvs=4
> Création d'une page statistiques pour chaque aide accessible depuis le portefeuille d'aide d'un contributeur

- src/alerts/urls.py
- src/exporting/utils.py
- src/geofr/admin.py
- src/geofr/forms/forms.py
- src/locales/fr/LC_MESSAGES/django.po
- src/minisites/urls.py
- src/projects/admin.py
- src/projects/resources.py
- src/upload/apps.py
https://www.notion.so/Retirer-les-appels-traduction-des-URLs-68a313cd93c140b08d3ed7034783db07?pvs=4
> Retirer les appels à traduction des URLs

- src/Pipfile
- src/Pipfile.lock
- src/projects/forms.py
https://www.notion.so/Mise-jour-de-Django-en-version-4-2-cddd05e799f246038bf4c0f113010ed5?pvs=4
> Mise à jour de Django en version 4.2

- src/static/js/aids/display_results_list.js
- src/templates/aids/_aid_result_as_list.html
- src/templates/aids/_results.html
https://www.notion.so/Am-liorer-l-accessibilit-des-boutons-d-affichage-liste-cartes-sur-la-page-de-r-sultats-75882c7f46cd49ab9329ec977f584234?pvs=4
> Améliorer l’accessibilité des boutons d’affichage liste/cartes sur la page de résultats

- src/templates/home/accessibility.html
https://www.notion.so/Accessibilit-G-rer-l-accessibilit-des-PDF-7c723c46313b46c4803365b8f96636e6?pvs=4
> Accessibilité - Gérer l’accessibilité des PDF

- src/core/settings/local.py
- src/core/settings/production.py
- src/core/settings/scalingo.py
- src/upload/tests/test_views.py
https://www.notion.so/Mettre-jour-les-param-trages-li-s-au-stockage-b2e19045240845f18e002de37f4e4cab?pvs=4
> Mettre à jour les paramétrages liés au stockage

- src/Makefile
- src/package-lock.json
- src/static/css/_custom.scss
- src/static/css/admin.css
- src/static/js/shared_config.js
- src/static/js/trumbowyg-resizimg/trumbowyg.resizimg-with-canvas-fix.js
Replaces the 4 snyk-generated PRs
https://www.notion.so/Mettre-jour-les-d-pendances-javascript-8ccf37cac2fd4b9b949c42f6245fa6dd?pvs=4
> Mettre à jour les dépendances Javascript

- src/accounts/admin.py
https://www.notion.so/Pouvoir-filtrer-par-d-partement-dans-l-admin-utilisateurs-5678cbd57ac1417891c1d5fd34136375?pvs=4
> Pouvoir filtrer par département dans l’admin/utilisateurs 

- src/aids/forms.py
- src/aids/templatetags/aids.py
- src/pages/views.py
- src/templates/aids/_search_form.html
- src/templates/aids/_search_meta.html
- src/templates/aids/advanced_search.html
- src/templates/minisites/_search_form.html
- src/templates/search/_search_form.html
https://www.notion.so/Cr-er-la-page-Europe-type-Fonds-Vert-4c159e447249493ebfaa7e322e1db309?pvs=4
> Ajoute un filtre `european-aid`

- src/templates/search/search_page.html
https://www.notion.so/Am-lioration-de-la-version-mobile-pour-la-page-portail-int-gr-et-cr-ation-du-logo-europe-a6bdca175e8145cca315c182cc46a37f?pvs=4
> Amélioration du responsive de la page portail intégré

- src/aids/services/export.py
- src/aids/urls.py
- src/aids/views.py
- src/templates/_base_pdf.html
- src/templates/aids/aid_export_pdf.html
- src/templates/aids/draft_list.html
https://www.notion.so/Donner-la-possibilit-au-contributeur-de-g-n-rer-le-pdf-de-chacune-de-ses-fiches-1-aide-par-fichier-fb734236283f4bac9609f59b9fdce1be?pvs=4
> Export du détail d'une aide en PDF depuis le portefeuille d'aides

- src/geofr/management/commands/populate_scots.py
- src/geofr/services/populate_scots.py
https://www.notion.so/Mise-jour-des-Sch-mas-de-coh-rence-territoriale-SCoTs-avec-les-donn-es-de-d-cembre-2022-6d9c2730bab040bcbcba626061171791?pvs=4
> Mise à jour des Schémas de cohérence territoriale (SCoTs) avec les données de décembre 2022

- src/templates/home/legal_mentions.html
https://www.notion.so/M-j-Mentions-l-gales-d2b53d35f55c4f12b0b5787ddbae3688?pvs=4
> Mise à jour des mentions légales : changement de directeur de la publication

- src/minisites/views.py
- src/search/sitemaps.py
- src/static/css/_custom.scss
- src/static/js/aids/targeted_audiences_autocomplete.js
- src/templates/aids/_base_search.html
- src/templates/alerts/_alert_modal.html
- src/templates/search/_search_form.html
- src/templates/search/search_page.html
https://www.notion.so/Pr-remplir-le-champ-email-lors-de-la-cr-ation-d-une-alerte-sur-un-portail-int-gr-si-l-utilisateur-e-656121fe784148dda7da423fbd5f547b?pvs=4
> Amélioration de l'affichage des portails intégrés

- src/geofr/management/commands/populate_pnr.py
- src/geofr/services/populate_pnr.py
https://www.notion.so/Mettre-jour-les-p-rim-tres-des-PNR-49344d07083b40a99250202b59a8d532?pvs=4
> Mettre à jour les périmètres des PNR

- src/.env.example
- src/core/settings/local.py
- src/dataproviders/tests/test_utils.py
- src/dataproviders/utils.py
- src/static/css/_custom.scss
- src/templates/_footer.html
- src/templates/_form_header.html
- src/templates/_header.html
- src/templates/accounts/_info_alert_modal.html
- src/templates/accounts/user_dashboard.html
- src/templates/aids/_base_edit.html
- src/templates/aids/_base_search.html
- src/templates/aids/_results.html
- src/templates/geofr/department_backers.html
- src/templates/home/contact.html
- src/templates/home/privacy_policy.html
- src/templates/minisites/stats.html
- src/templates/projects/_projects_result_as_list.html
- src/templates/search/search_page.html
- src/templates/stats/stats.html
https://www.notion.so/Passe-de-v-rification-de-l-accessibilit-sur-toutes-les-pages-a6634b124bf5499194ca27abef7640e6?pvs=4
> Passe de vérification de l’accessibilité sur toutes les pages

- src/aids/forms.py
- src/core/utils.py
- src/projects/forms.py
- src/stats/models.py
https://www.notion.so/Bug-nettoyer-les-caract-res-nuls-dans-les-champs-de-recherche-texte-libre-94b1f25a8fa6433cbe9fcc03db334b40?pvs=4
> Bug - nettoyer les caractères nuls dans les champs de recherche texte libre

- src/backers/views.py
- src/templates/aids/_aid_result_as_list.html
https://www.notion.so/Page-porteur-tableau-des-aides-ajouter-le-p-rim-tre-88bb552944d44cc0a0393f4c2bec6066?pvs=4
> Ajouter le périmètre des aides sur la page détail porteur

- src/accounts/forms.py
- src/organizations/forms.py
https://www.notion.so/Corriger-la-typo-sur-la-page-d-inscription-bbe73db89514409992ccfd45502c3bad?pvs=4
> Correction d'une typo sur le formulaire d'inscription 

- src/accounts/resources.py
https://www.notion.so/Ajouter-le-champs-type-d-intercommunalit-de-la-structure-dans-l-extract-utilisateurs-85d54ec21a72440baf8c32a1b89c8311?pvs=4
> Ajout du champs “type d’intercommunalité” de la structure dans l’extract utilisateurs

- src/accounts/signals.py
- src/minisites/tests/test_views.py
- src/search/tests/test_views.py
https://www.notion.so/Bug-Pouvoir-supprimer-un-compte-utilisateur-sans-organisation-depuis-l-administration-c243e7c1a4b84d4fb6a374365e81d0e4?pvs=4
> [Bug] Pouvoir supprimer un compte utilisateur sans organisation depuis l’administration

- src/templates/home/legal_mentions.html
https://www.notion.so/m-j-mentions-l-gales-2028baa719ce486c957d5123fec06977?pvs=4
> Modification du nom du responsable de publication

- src/aids/views.py
https://www.notion.so/Fix-accepter-une-aide-sugg-r-e-n-ayant-plus-de-sugg-rant-enregistr-en-base-9b539ae5ec194eeda887aaca563e702e?pvs=4
> Fix : une aide suggérée peut être ajoutée à un projet même si le suggérant n'existe plus en base

- src/home/urls.py
- src/templates/home/cgu.html
- src/templates/home/legal_mentions.html
- src/templates/home/sitemap.html
https://www.notion.so/Cr-er-et-mettre-en-ligne-la-page-CGU-9419c4d1a17b48d7acaf52319c06e359?pvs=4
> Ajout d'une page CGU

- src/templates/aids/_aid_result.html
https://www.notion.so/Retours-contre-audit-accessibilit-f7b914c1a7e34c65ab333d98e2e0f685?pvs=4
> Retours contre-audit accessibilité

- src/Pipfile
- src/Pipfile.lock
- src/accounts/admin.py
- src/core/filters.py
- src/core/settings/base.py
- src/exporting/tasks.py
- src/geofr/admin.py
- src/geofr/models.py
- src/geofr/resources.py
- src/templates/_header.html
- src/templates/admin/dropdown_filter.html
https://www.notion.so/Pouvoir-cr-er-des-p-rim-tres-partir-de-la-population-de-la-commune-9981a5d6675b44a6af5d6dd7406504ff?pvs=4
> Pouvoir créer des périmètres à partir de la population de la commune

- src/aids/management/commands/export_aids_for_collectivities.py
- src/aids/models.py
- src/aids/services/export.py
https://www.notion.so/Lister-les-aides-destin-es-aux-collectivit-s-territoriales-communes-EPCI-d-partements-r-gions-c-b4dd20aa87e74250b0834874305d2e1e?pvs=4
> Lister les aides destinées aux collectivités territoriales sur la période 2019-2022

- src/accounts/models.py
- src/aids/forms.py
- src/aids/views.py
- src/notifications/forms.py
- src/templates/projects/_create_or_update_project_form.html
- src/templates/projects/_suggest_aid_modal.html
- src/templates/projects/project_detail.html
https://www.notion.so/Suggestion-d-aides-mettre-un-encart-pour-permettre-d-adresser-un-message-la-collectivit-laque-4b1d9908555c4e6facd3b876fe75477d?pvs=4
> Suggestion d’aides : mettre un encart pour permettre d'adresser un message à la collectivité à laquelle on suggère une aide

- src/aids/views.py
- src/static/js/plugins/datatables_i18n.js
- src/templates/aids/draft_list.html
https://www.notion.so/Am-liorer-le-filtrage-tri-dans-le-portefeuille-d-aides-des-contributeurs-3-demandes-436a986091aa43969c493d6076e2fd02?pvs=4
> Améliorer le filtrage / tri dans le portefeuille d’aides des contributeurs (3 demandes)

- src/Makefile
- src/aids/views.py
- src/minisites/views.py
- src/templates/aids/detail.html
- src/templates/search/_search_form.html
https://www.notion.so/Am-liorer-les-portails-personnalis-s-c80d5aa8ef4145eeb5e23cf5a5b90929?pvs=4
> Améliorer les portails personnalisés

- src/aids/services/export.py
- src/aids/templatetags/aids.py
- src/aids/views.py
- src/templates/_base_pdf.html
- src/templates/aids/aid_export_pdf.html
- src/templates/aids/aids_export_pdf.html
- src/templates/aids/detail.html
https://www.notion.so/Am-liorer-le-catalogue-des-aides-que-le-contributeur-peut-t-l-charger-6-demandes-cfad96f573c6451a8a3d207c4ac5fb85?pvs=4
> Améliorer le catalogue des aides que le contributeur peut télécharger (6 demandes)

- src/minisites/urls.py
- src/minisites/views.py
- src/templates/home/cgu.html
- src/templates/minisites/cgu.html
https://www.notion.so/BUG-Affichage-des-CGU-sur-les-portails-89bb6bf22694482eb8962a909275460f?pvs=4
> BUG - Affichage des CGU sur les portails

- src/dataproviders/management/commands/base.py
https://www.notion.so/BUG-Mise-jour-des-dates-de-cl-ture-des-aides-du-flux-du-Minist-re-de-la-culture-9269fc29eb1044d6bc064d26172dedbc?pvs=4
> BUG - Mise à jour des dates de clôture des aides du flux du Ministère de la culture
