MTES-MCT/aides-territoires

- deployment/roles/appservers/tasks/cron.yml
Mise à jour du script de déploiement avec l'ajout d'une tâche quotidienne pour importer les données de l'ademe.
https://trello.com/c/zGEz6kV1/207-activer-limport-ademe-hebdomadairement
> Ajoute l'import quotidien des données de l'Ademe

- src/aids/management/commands/new_aids_alert.py
Au lieu d'envoyer une alerte pour les aides publiées la veille, considérer *toutes* les aides (même celles en brouillon).
> Alertes pour les nouvelles aides

- src/templates/accounts/login_success.html
Lors de la création de compte, le "félicitations" n'est pas centré par rapport au texte " vous êtes désormais contributeur" (ou équivalent)
=> à centrer si possible
https://trello.com/c/wV1lQRL3
> Center "Congratulations!"

- src/backers/admin.py
Ll'admin peut trier les apporteurs par ordre alphabétique (et par nb d'aides portées)
https://trello.com/c/JckWMfsG
> Trier les apporteurs par ordre alphabétique

- src/aids/forms.py
- src/aids/tests/test_search_engine.py
- src/templates/aids/_search_form.html
- src/templates/aids/advanced_search.html
https://trello.com/c/Mi7lLC7B/282-enlever-la-coche-aides-ajout%C3%A9es-au-cours-des-30-derniers-jours-dans-la-recherche-avanc%C3%A9e
> Supprime le filtre « aides récentes seulement »

- src/aids/forms.py
https://trello.com/c/swxC9OhP/252-probl%C3%A8me-sur-le-remplissage-de-fiche-champ-mot-cl%C3%A9
Bug provoqué par le passage à django 2.2.
https://docs.djangoproject.com/en/dev/releases/2.2/#merging-of-form-media-assets
> Corrige l'autocomplétion des tags en admin

- src/aids/forms.py
- src/dataproviders/management/commands/import_grand_est.py
- src/dataproviders/scrapers/grand_est.py
- src/templates/aids/detail.html
La section « origine de la donnée » (page de détail des aides) s'affichait de manière incorrecte (affichage de « None » et de valeurs vides).
J'ai ajouté des valeurs par défaut.
J'en ai profité pour corriger quelques tâches d'imports qui n'étaient plus fonctionnelles.
https://trello.com/c/eqfXhDVC/269-v%C3%A9rifier-laffichage-de-la-section-origine-de-la-donn%C3%A9e
> Affichage correct de la section « origine de la donnée »

- src/static/css/custom.scss
Ex : sur la page d'accueil, faire une recherche sur « Marseille ».
> Corrige le problème de rendu pour les long périmètres

- src/templates/_anonymous_menu.html
Après la connexion, redirige l'utilisateur vers la page courante.
https://trello.com/c/mPsoD0mI/391-changer-la-redirection-lors-de-la-connexion-sur-at
Puisque nous utilisons la [vue django standard](https://docs.djangoproject.com/fr/2.2/topics/auth/default/#django.contrib.auth.views.LoginView) pour le login, c'est aussi simple que d'ajouter un champ caché « next ».
> Corrige la redirection après le login

- src/package-lock.json
- src/package.json
- src/static/css/styles.scss
Utilise les [nouveaux *responsive containers*](https://getbootstrap.com/docs/4.4/layout/overview/#containers) disponibles dans la nouvelle version de Bootstrap pour maximiser la taille du layout sur les petits écrans.
> Corrige un problème de mise en page sur petits écrans

- deployment/roles/appservers/tasks/packages.yml
Nodejs 8 is obsolete: https://nodejs.org/en/about/releases/
> chore: upgrade nodejs

- deployment/roles/appservers/tasks/user.yml
Fixes Issue #161
Ajout d'une tache supplémentaire avant écriture dans le fichier `.bashrc` afin de s'assurer que le fichier existe bien.
La propriété `changed_when` permet de terminer la tache en statut `ok` si le fichier existe déjà. 
En effet le module `file` exécuté avec `state: touch` semble renvoyer systématiquement le statut `changed`.
https://github.com/ansible/ansible/issues/30226#issuecomment-328952676
> fix missing .bashrc file during ansible deployment

- src/minisites/views.py
- src/templates/minisites/search_page.html
https://trello.com/c/JBhUSFn7/617-ajouter-les-indications-durl-canoniques-entre-les-diff%C3%A9rents-sites
Les pages de recherche pouvant exister derrière plusieurs domaines sont dé-doublonnées au moyen d'une indication d'url canonique.
> Ajoute une indication d'url canonique sur les minisites

- .travis.yml
Fixes MTES-MCT/aides-territoires#180: add travis_retry before wget to prevent build failures not linked to commit
> Fixes MTES-MCT/aides-territoires#180: add travis_retry before wget

- src/.env.example
Ajout du paramètre `SIB_LIST_ID=24` au fichier `.env.example` afin d'éviter une erreur lors de la commande `ansible-playbook -i hosts -l local site.yml`
> add SIB-LIST-ID to .env.example

- src/static/css/_globals.scss
- src/templates/minisites/_css.html
Correction d'un bug d'affichage des h1 after (au zoom ou dezoom apparition d'un espace vide dans la barre de soulignement).
> correct h1 after bg-color

- src/templates/minisites/_css.html
- src/templates/minisites/_footer.html
- src/templates/minisites/_header.html
Correction de deux erreurs concernants les minisites : 
- la page plantait si les champs `color_3` ou `color_4` étaient vides
- la page plantait si le champs `logo` était vide
> Minisites : corrige des erreurs d'affichage

- src/templates/minisites/_css.html
Changement de la max-width du logo partenaire dans le header des PP afin d'éviter l'anamorphose des doubles logos (ex: arc de l'innovation Paris&co).
> update max-width partner-link-img

- src/locales/fr/LC_MESSAGES/django.po
- src/templates/_anonymous_menu.html
- src/templates/_js_i18n.html
- src/templates/data/doc.html
- Ajout de l'écriture inclusive
- `Porteurs d'aides` --> `Porteur·s d'aides`
- `Contact(s)` --> `Contact·s`
- etc.
- Remplacement de "financeur" par "porteur d'aides"
- typos
- `Enregister` --> `Enregistrer`
> Fix des typos et rajoute de l'écriture inclusive

- Pipfile
- Pipfile.lock
- src/aids/admin.py
- src/core/settings/base.py
Modifications apportées:
- ajout de la librairie `django-import-export` (doc [ici](https://django-import-export.readthedocs.io/en/latest/index.html))
- ajout d'une action "Export des aides séléctionnés" dans l'admin, pour le modèle Aid
- 3 formats d'export possible : csv, xls & xslx
> Export : aides séléctionnées dans l'admin

- src/minisites/tests/test_views.py
- src/search/models.py
Somethime, the admin person enters a question mark in the initial
querystring. That should not break the filtering.
> Minisites querystring: fix an issue with the prefix question mark

- src/aids/admin.py
Dans la continuité de https://github.com/MTES-MCT/aides-territoires/pull/227
L'overriding de la librairie django-import-export se fait en regardant le contenu de la librairie ici : https://github.com/django-import-export/django-import-export/tree/master/import_export
> Export : aides séléctionnées dans l'admin : Améliorations

- src/dataproviders/management/commands/base.py
- src/dataproviders/management/commands/import_nouvelle_aquitaine.py
But : importer des aides contenues dans 2 fichiers XML provenant de l'ADDNA (Aides pour le Développement Durable en Nouvelle-Aquitaine). Environ 400 aides.
- ajout d'une management command `dataproviders/management/commands/import_nouvelle_aquitaine.py` qui importe un fichier XML à la fois
- chaque management command de dataproviders hérite de `base.py`. Mais certaines erreurs etaient mal gérés, d'où l'ajout d'un try/except pour être plus clair dans les erreurs soulevées
- pour aider à la relecture dans l'admin lors de la validation de l'aide, j'ai mis certaines metadata de l'aide dans le champs `project_examples`
Exemple d'aide dans le XML : 
```
(...)
<table name="p">
<column name="id">79</column>
<column name="url">NULL</column>
<column name="name">Appel à …
```
> Import : aides provenant de l'ADDNA (format xml)

- src/accounts/tests/test_views.py
- src/aids/admin.py
- src/backers/admin.py
Suite aux tests de https://github.com/MTES-MCT/aides-territoires/pull/228 & https://github.com/MTES-MCT/aides-territoires/pull/230
Import de porteurs d'aides : 
- enlever le champ `is_corporate`
- enlever le format XLS
Export d'aides : 
- enlever le format XLS
> Améliorations pour l'import et l'export dans l'admin

- src/geofr/admin_views.py
- src/geofr/forms/forms.py
- src/geofr/tests/test_utils.py
- src/geofr/utils.py
- src/locales/fr/LC_MESSAGES/django.po
- src/templates/admin/geofr/perimeter/submit_line.html
- src/templates/admin/perimeter_combine.html
- src/templates/admin/perimeter_upload.html
Modifications apportées :
- rajout d'une option d'import d'une liste d'EPCI. Il y a donc maintenant 2 options: une liste de communes (code INSEE), ou une liste d'EPCI (noms)
- les messages d'erreurs sont plus claires
- renvoi d'erreurs si des communes (ou EPCIs) fournies dans la liste sont absents de la base de donnée
Le workflow reste le même : 
1. créer un périmètre (ou sélectionner un périmètre ad-hoc existant)
2. cliquer sur le bouton "Uploader la liste des périmètres" en bas
3. le formulaire d'import apparait
4. si le formulaire ne renvoie pas d'erreurs, le périmètre est mis à jour
étape 3 du workflow : le formulaire d'import, qui a été enrichi
> Amélioration de l'upload de périmètres

- src/aids/admin.py
Dans la continuité de https://github.com/MTES-MCT/aides-territoires/pull/227 & https://github.com/MTES-MCT/aides-territoires/pull/230
Répare un bug sur l'export : les aides avec un subvention_rate provoquaient une erreur au moment de l'export
> Export : aides séléctionnées dans l'admin : fix

- deployment/group_vars/prod.yml
Ajout des sous-domaines : 
- france-relance-normandie
- france-relance-grand-est
- france-relance-cvl
- france-relance-guyane
> add minisites FrRel Guyane, Normandie, cvl, grand-est

- src/static/js/search/track_category_step_events.js
- src/static/js/search/track_theme_step_events.js
Utilise la value de l'input plutôt que le texte du label pour transmettre les thèmes et catégories sélectionnés à Matomo. 
Cela permet de transmettre à Matomo le nom du thème ou de la catégorie sans le nombre variable de résultats associé à ce thème ou à cette catégorie. 
[ticket trello relevant le problème](https://trello.com/c/oilbk1sV/762-donn%C3%A9es-matomo-erron%C3%A9es)
> use input instead of label to pass to matomo

- src/alerts/admin.py
Actuellement il est impossible de retrouver facilement une alerte.
Cette PR rajoute un search par email en haut.
> Pouvoir chercher par email dans Admin > Alerts

- src/templates/search/step_audience.html
- src/templates/search/step_category.html
- src/templates/search/step_theme.html
Ajout des fichiers `track_category_step_events.js` , `track_theme_step_events.js` , et `track_audience_step_events.js` au fichier js global compressé. 
Cela résoud un souci d'absence de mise à jour des fichiers js gardés abusivement en cache par le navigateur.
> add matomo-track-files to compress js file

- src/templates/_footer.html
- src/templates/minisites/_footer.html
Correction de typo dans le footer d'Aides-territoires et dans celui des sous-domaines : 
- ajout du bon lien pour le logo du Ministère de la Cohésion
- modification du format du téléphone dans le footer des pages personnalisées.
> fix typo footer

- src/.gitignore
- src/categories/fields.py
- src/static/css/_globals.scss
https://trello.com/c/CQJXyZxK/565-formulaire-pp-revoir-la-s%C3%A9lection-des-th%C3%A9matiques-ss-th%C3%A9matiques
Modifications apportées
- les sous-thématiques sont groupées par thématiques dans le select
- on affiche seulement le nom de la sous-thématique et non "THEMATIQUE > sous-thématique"
> Ajustements cosmétiques sur le filtrage sous-thématiques

- src/aids/tests/test_forms.py
- src/core/forms/fields.py
- src/dataproviders/utils.py
- src/static/js/trumbowyg-resizimg/trumbowyg.resizimg-with-canvas-fix.js
- src/upload/settings.py
À propos du bug :
- La source du problème est décrit ici : https://github.com/Alex-D/Trumbowyg/issues/1158
- Le tag `img` est parfois transformé en tag `canvas`. Ça ne devrait déjà pas arriver.
- En plus, comme nous avons un cleanup-backend des tags avant la sauvegarde, le tag `canvas` disparaît tout simplement.
Ma proposition pour avancer : 
> - I have imported a copy of the resizimg JS plugin
> - Instead of loading the upstream version, I'm using that local version of the plugin.
> - This is a temporary fix and we should get back to using upstream once the fix is released.
J'ai mis un message dans le dépôt GIT de Trumbowyg pour motivé l'application du patch et une nouvelle release.
> Problème d'image non affichée quand on la redimensionne

- src/static/css/_custom.scss
Corrige un bug d'affichage lors de la prévisualisation d'une aide par un contributeur avec le navigateur Safari. https://trello.com/c/MokcAFa8/767-pr%C3%A9visualisation-des-aides
La fenêtre pop-up permettant la prévisualisation de l'aide réduit le contenu de l'iframe et remplit quasi totalement la fenêtre en blanc). Ce bug d'affichage de l'iframe semble être classique sur Safari.  
Ajout des propriétés `width`, `height` et `overflow-y` à la div parente de l'iframe afin de forcer l'affichage de l'iframe avec la bonne `height`.
> fix bug aids-previsualisation-with-safari-browser

- src/templates/_footer.html
Modifie l'url utilisée dans le footer pour le bouton "`contribuez"/"connectez-vous et contribuez`". 
Que l'utilisateur soit connecté ou non on utilise le lien `{% url 'aid_draft_list_view' %}` car la view `AirDraftListView `contrôle déjà si l'utilisateur est connecté et renvoi à la page connection si ça n'est pas le cas grâce à la class `ContributorRequiredMixin`
Cela règle un problème de renvoi systématique au formulaire de mise à jour du profil contributeur. 
https://trello.com/c/ydFzOUCu/766-page-daccueil-porteur-daide
> change url for contribute-btn

- src/home/urls.py
- src/home/views.py
- src/locales/fr/LC_MESSAGES/django.po
- src/templates/home/addna_optin.html
https://trello.com/c/i3YSKwGN/810-mise-en-place-de-loptin-pour-les-alertes-addna
Création d'une url spécifique qui sera mentionnée dans la campagne ADDNA.
Depuis Sendinblue, il sera ensuite possible de créer un filtre pour extraire les contacts ayant cliqués sur ce lien.
> Créé une page de confirmation d'optin pour les contacts ADDNA

- src/aids/admin.py
- src/locales/fr/LC_MESSAGES/django.po
https://trello.com/c/8T6tJKz2/803-am%C3%A9liorations-de-loutil-dexport-xls
- Enlever une 10aine de champs de l'export
- Rajouter le champ 'Programmes' qui manquait à l'export
> Admin : enlever certains champs lors de l'export d'aides

- src/aids/admin.py
- src/pages/admin.py
- src/search/admin.py
- src/static/js/enable_rich_text_editor_simple.js
- src/static/js/shared_config.js
- src/templates/_base.html
- src/templates/admin/amend_ui.html
- src/templates/aids/_base_edit.html
Il y a maintenant 2 fichiers JS pour la configuration Trubmowyg : Pour les admins et pour les porteurs d'aides non-admin.
On a aussi rajouté la notion de "shared config" pour qu'on ai un endroit où mettre les variables JS qui sont partagées.
```
Text Field: The image button is now only available for admin
There is a new JS file for shared config. That's where we put
variables that we need to share across several JS modules.
Typically, the Trumbowyg config is one of these variables,
since we have a config for site users and a slightly different
config to site admin.
```
https://trello.com/c/KlmODeqj/808-upload-dimage-dans-la-section-non-admin-on-ne-doit-pas-pouvoir-uploader-des-images
> L'upload d'images restreint aux admins

- src/backers/api/views.py
- src/backers/factories.py
- src/backers/models.py
- src/backers/tests/test_api.py
- src/backers/tests/test_models.py
- src/static/js/aids/backers_autocomplete.js
https://trello.com/c/4217jS5q/779-am%C3%A9liorer-la-liste-d%C3%A9roulante-des-porteurs-daides
- Dans le formulaire de recherche d'aide (simple et avancé), on affiche seulement les porteurs d'aides qui sont 'financeurs' et qui ont des aides publiées
- 2 nouveaux queryset dans le modèle `Backer`
- Ajout de filtres dans l'API du modèle `Backer`
- Ajout de tests
> Filtre sur les Porteurs d'aides dans la recherche

- Pipfile
- Pipfile.lock
- src/aids/admin.py
- src/aids/forms.py
- src/core/settings/base.py
- src/geofr/tests/test_utils.py
- src/geofr/utils.py
https://trello.com/c/kTiYjojW/804-nouveaux-champs-de-filtrage-dans-ladmin
- ajout d'un filtre "par Programmes"
- ajout d'un filtre "par Sous-thématiques"
- remplace le filtre "par Périmètres"
- avant : recherche simple sur le nom + filtre exacte sur les aides ayant ce périmètre
- après : recherche autocomplete (select2) + filtre habituel des périmètres (toutes les aides ayant ce périmètre + incluses dans ce périmètre)
Pour cette dernière modif j'ai du installer un package additionnel, [django-admin-autocomplete-filter](https://github.com/farhan0581/django-admin-autocomplete-filter) car par défaut l'autocomplete est seulement disponible lors de la modification d'une aide, pas dans les filtres de la page list
Avant / Après
<p>
</p>
> Admin : rajoute des filtres dans le modèle Aid

- src/aids/forms.py
Correction d'un bug liée à la [PR](https://github.com/MTES-MCT/aides-territoires/commit/b47d6d304b101581870eb0ac6c663d9e6b5aa211) rendant obligatoire le champ `mobilization_steps` sur la page d'édition d'une aide. 
La page admin/amendment renvoi actuellement une erreur visant le champ `mobilization_steps` (https://trello.com/c/RO9nfOuY/812-bug-sur-la-page-admin-amendements-mobilizationsteps)
Ajout d'une condition dans la class `AidEditForm` pour rendre obligatoire le champ `mobilization_steps`.
> Corrige un bug sur la page admin/amendment - mobilization_steps

- src/aids/forms.py
- src/categories/fields.py
https://trello.com/c/CQJXyZxK/565-formulaire-pp-revoir-la-s%C3%A9lection-des-th%C3%A9matiques-ss-th%C3%A9matiques
Dans la continuité de https://github.com/MTES-MCT/aides-territoires/pull/261
Le grouping par thématique cassait les formulaires dans l'admin. Du coup le grouping n'a plus lieu de façon automatique, et seulement dans BaseAidSearchForm
> Filtrage par sous-thématique: restreindre à seulement l'interface

- src/templates/aids/_search_form.html
Trello: https://trello.com/c/tV6yDEX1/757-recherche-daide-probl%C3%A8me-de-filtrage-sur-le-site-principal
Il y avait un bug :
- On est dans la page de recherche avancée et on cherche par "programmes"
- La page de résultat s'affiche bien.
- Mais quand on retourne dans la recherche avancée, le programme n'est plus là.
Il manquait le champs caché "programs" dans le formulaire principal, c'est pour ça...
> Add a missing hidden field for prgrams on search form page

- src/aids/views.py
- src/templates/aids/draft_list.html
https://trello.com/c/vGTvsCs6/796-portefeuille-daide-mise-en-forme-des-colonnes
- colonne "Nom" devient "Nom de l'aide"
- le tri par défaut est maintenant "les plus récemment modifiées en haut"
> Portefeuille d'aides : change le tri et le nom d'une colonne

- src/aids/views.py
- src/locales/fr/LC_MESSAGES/django.po
- src/static/css/_custom.scss
- src/static/css/_globals.scss
- src/templates/aids/draft_list.html
https://trello.com/c/3ZUHpmMX/798-portefeuille-daide-nouveaux-indicateurs-dashboard
Modifications apportée : 
- 2 nouveaux indicateurs de nombre de vues s'affichent en haut du portefeuille d'aides
> Portefeuille d'aides : affiche le nombre de vues totales en haut

- src/backers/tests/test_views.py
- src/backers/urls.py
- src/backers/views.py
- src/core/urls.py
- src/locales/fr/LC_MESSAGES/django.po
- src/templates/backers/detail.html
Trello : https://trello.com/c/3AxE7y5S/825-ajouter-la-nouvelle-page-porteur-daide
Une page qui affiche la description du porteur d'aide.
> Ajout de la page du porteur d'aide

- src/aids/admin.py
- src/aids/forms.py
- src/aids/models.py
- src/aids/tests/test_managers.py
- src/aids/views.py
- src/locales/fr/LC_MESSAGES/django.po
- src/static/css/_custom.scss
- src/templates/aids/draft_list.html
https://trello.com/c/331qllvG/795-affichage-du-statut-de-laide-dans-le-portefeuille-daide
- ajout d'un formulaire de filtres en haut, qui permet de filtrer sur "l'état" et "l'affichage" des aides de son portefeuille
- Les 3 états possibles d'une aide sont : Ouverte, Expire bientôt (< 30 jours), Expirée
- Les 2 affichages possibles d'une aide sont : Non affichée, Affichée (= live)
- Ajout d'un icône dans la colonne Nom qui indique que l'aide est Affichée
- Ajout d'icônes dans la colonne Echéance qui indiquent que l'aide Expire bientôt ou est Expirée
- Ajout du queryset `open()` dans le modèle Aid (+ test)
> Portefeuille d'aides : filtres par statut, état et affichage

- src/home/views.py
- src/static/css/_custom.scss
- src/static/js/carousel.js
- src/templates/home/home.html
Complète la PR #295. 
Suite de la carte https://trello.com/c/q6gKEik3/628-simplification-de-laffichage-des-logos-sur-la-page-daccueil
Création d'un carousel pour afficher dynamiquement les logos des porteurs sur la page `Home`.
> create carousel to display backers-logos in Homepage

- src/aids/views.py
- src/static/css/_globals.scss
Correction pour mise en prod de la carte https://trello.com/c/xYhIRrU7/794-option-d%C3%A9ditions-dune-aide
Auparavant, lorsque l'utilisateur cliquait sur le bouton `dupliquer l'aide` il était renvoyé sur la page d'édition de la nouvelle aide et l'iframe de prévisualisation de l'aide apparaissait automatiquement. On supprime ce comportement pour que l'utilisateur soit renvoyée vers la page d'édition de la nouvelle aide sans prévisualisation. 
`Font-weight: bold` pour le `<p>` warning indiquant que la nouvelle aide a été créée.
> Edition d'une aide - correction à la marge

- src/aids/forms.py
- src/locales/fr/LC_MESSAGES/django.po
- src/static/css/_custom.scss
- src/templates/aids/draft_list.html
Dans la continuité de https://github.com/MTES-MCT/aides-territoires/pull/292
- Renomage de certains labels
- Ajout d'un message pour indiquer que les colonnes sont triables + ajout de `title=` sur le nom des colonnes
- Ajout d'un icône "P" dans la colonne Échéance pour indiquer les aides permanentes
- Afficher tout le temps le nombre de vues par aide (avant : seulement si l'aide était au Statut publiée)
- Ajustement du formattage du code html 😅
> Portefeuille d'aides : corrections à la marge

- src/aids/views.py
- src/templates/aids/detail.html
https://trello.com/c/jFmspMsa/815-fiche-aide-affichage-crit%C3%A8res-d%C3%A9ligibilit%C3%A9
Conditionne l'affichage du `h2` "critères d'éligibilité" à la présence d'un de ces champs : 
-  `mobilization_steps`
- `destinations `
- `project_examples` 
- `eligibility`
> Conditionne l'affichage du titre "critères d'éligibilité" sur la page AidDetail

- src/minisites/mixins.py
https://trello.com/c/tWraMYk1/832-bug-affichage-cat%C3%A9gories
Une même thématique pouvait s'afficher plusieurs fois dans le champ de filtrage par catégories.
> Corrige un bug de sélection des catégories

- src/aids/forms.py
https://trello.com/c/wjvbBYRf/834-rendre-obligatoire-le-choix-dune-th%C3%A9matique-dans-le-formulaire-de-cr%C3%A9ation-daide
Il était possible de créer une aide sans choisir de thématique.
> Rend obligatoire le choix d'une thématique pour la création d'une aide

- src/templates/aids/edit.html
La balise <a> du message affiché lors de la création d'une aide par un porteur était échappée. 
https://trello.com/c/O7S4nUcE/836-bug-notification-aide-publi%C3%A9e
> Correction de l'affichage du message lors de la création d'une aide

- src/templates/aids/detail.html
Sur la page AidDetail l'url des images n'était pas construite correctement.
> Modifie la construction de l'url des images

- src/static/css/admin.css
- src/static/js/aids/duplicate_buster.js
https://trello.com/c/5Vpi2PBV/848-d%C3%A9place-le-message-davertissement-alerte-doublons-dans-ladmin
Pour tester : modifier l'aide et spécifier une url d'origine correspondante à une aide existante.
> Déplace le message d'alerte doublons sous le champ "lien d'origine"

- src/aids/admin.py
- src/aids/tests/test_utils.py
- src/aids/utils.py
https://trello.com/c/SFH4ni06/838-duplication-daide-identifier-les-aides-dupliqu%C3%
Pour tester, éditer une aide dans l'admin, et cliquer sur « Enregistrer en tant que nouveau ». Constater le titre de la nouvelle aide ainsi créée.
> Préfixe le titre des aides dupliquées en admin

- src/aids/views.py
- src/static/css/_custom.scss
- src/templates/aids/draft_list.html
https://trello.com/c/HtAr5f9O/840-portefeuille-daide-affichage-p%C3%A9rim%C3%A9tres
https://trello.com/c/9sxm8ayV/842-portefeuille-daide-titre-aide
- Nouvelle colonne qui affiche le périmètre de l'aide, avec possibilité d'ordonner par cette colonne
- Afficher le Nom complet de l'aide, donc il y aura parfois un retour à la ligne
- La largeur de la colonne Nom est fixée à 50%
> Portefeuille d'aides : nouvelle colonne périmètre

- src/locales/fr/LC_MESSAGES/django.po
- src/static/css/_custom.scss
- src/templates/programs/detail.html
- Modification du design de la page programme (à laquelle on accède maintenant en cliquant sur le logo programme sur les Fiches AideDetail). 
- Modification du design de la `div` logos sur la Fiche Aide afin de cacher la `div` si aucun logo n'est affiché. 
- Correction lien top-footer erroné dans le fichier `django.po`.
> Correction bug design Fiche Programme, Fiche Aide et bug lien top-footer PP

- src/templates/aids/detail.html
Le commentaire sur le taux de subvention ne pouvait s'afficher que si un taux de subvention était renseigné. 
https://trello.com/c/urRtPPYT/850-affichage-du-commentaire-sur-le-taux-de-subvention-sur-la-fiche-aide
> Affichage du commentaire sur le taux de subvention sur les Fiches Aide

- src/aids/admin.py
- src/minisites/views.py
- src/stats/utils.py
Dans certains environments (staging, local), on a pas les infos nécessaires pour échanger avec Matomo. Du coup afficher 0 pour ces stats là. Cela faisait planter la page stats des minisites sinon.
Bug Sentry en staging : https://sentry.io/organizations/aides-territoires-beta/issues/2093983588/?project=5506818&referrer=slack
> Minisites : meilleur gestion des stats renvoyées par Matomo

- src/Procfile
- src/scripts/start.sh
Un nouvelle proposition pour mettre le site en français : faire tourner la commande `compilemessages` systématiquement avant de lancer gunicorn.
J'ai vérifié que ça fonctionne aussi quand on redémarre le centenaire scalingo - parce que le script de démarrage qui contient les commandes `compilemessages + gunicorn` est lancé à chaque fois.
> Sur Scalingo, le site ne s’affiche pas en français V2

- src/static/css/_custom.scss
- src/templates/aids/_aid_result.html
https://trello.com/c/h3rhLMfm/860-affichage-r%C3%A9sultats-ajout-s%C3%A9parateur
> Ajout d'un séparateur '|' entre les types d'aides sur les cartes des aides. 

- src/backers/admin.py
- src/backers/models.py
- src/home/views.py
- src/locales/fr/LC_MESSAGES/django.po
- src/static/js/carousel.js
- src/templates/home/home.html
https://trello.com/c/hEhKZK5r/875-pouvoir-filter-les-porteurs-par-logo
Dans la continuité de https://github.com/MTES-MCT/aides-territoires/pull/338, j'ai voulu tester les pages porteurs en local, mais je n'avais pas de logo, et du coup j'ai vu pas mal de bugs / améliorations. Les voici 😅 👇 
- Afficher dans l'admin si le porteur a un logo ou pas
- Pouvoir filtrer dans l'admin les porteurs avec logo
- Ajout de 2 QuerySet dans le modèle Backers pour pouvoir plus facilement filtrer les porteurs avec logo
- Fix de l'affichage dans la home page : les porteurs qui etaient spotlighté mais sans logo étaient quand même affichés dans le carousel
- Refactoring du carousel.js
Pourquoi avoir remplacer le filtre `logo__isnull=False` par `Q(logo='') | Q(logo=None)` ?
- Les porteurs ont par défaut `logo = …
> Porteurs d'aides : Améliorations de la gestion des logos

- src/locales/fr/LC_MESSAGES/django.po
- src/static/css/_custom.scss
- src/templates/aids/_search_form.html
**(Recréation de la PR #331 pour déploiement de la reviewApp sur Scalingo).**
https://trello.com/c/CRzbM0ZQ/732-changement-de-texte-cartouche-plus-de-crit%C3%A8res
Dans le formulaire "plus de critères" on remplace le champ AAP / AMI uniquement par Appels à projets / Appels à manifestation d’intérêt uniquement
>   Modification du champ AAP/AMI dans le cartouche "plus de critères" 

- src/backers/views.py
- src/core/settings/scalingo.py
- src/core/urls.py
- src/locales/fr/LC_MESSAGES/django.po
- src/static/css/_custom.scss
- src/static/css/_theme.scss
- src/templates/backers/detail.html
Première partie de la carte https://trello.com/c/lbNwvDST/843-fiche-porteur-en-admin-sur-at-affichage-des-th%C3%A9matiques-des-aides.
Permet l'affichage sur chaque page porteur, des thématiques, catégories et programmes associés aux aides de ce porteur.
- Dans le fichier `backers/views.py`, ajout d'une `def get_context` pour récupérer les thématiques, catégories et programmes associés aux aides du porteur.
- Dans le fichier `templates/backers/detail.html`, ajout d'une section pour l'affichage des thématiques, catégories et programmes.
- Ajout du style dans le fichier `_custom.scss`
> Ajout des thématiques et programmes associés sur les pages Porteur. 

- src/templates/aids/_aid_result.html
https://trello.com/c/QoKJ82cM/885-conditionne-laffichage-du-titre-%C3%A9ch%C3%A9ance-sur-les-cartes-de-r%C3%A9sultats-des-aides
Conditionne l'affichage du titre 'échéance' à l'existence d'une date d'échéance sur les cartes de résultats des aides.
> Conditionne l'affichage du titre "échéance" sur les cartes de résultats des aides

- src/aids/views.py
- src/locales/fr/LC_MESSAGES/django.po
https://trello.com/c/DPbXG4lf/859-modifie-le-message-lors-de-la-duplication-dune-aide
Modification du message affiché lors de la duplication d'une aide.
> Modifie le message lors de la duplication d'une aide 

- src/aids/api/views.py
- src/aids/tests/test_api.py
- src/conftest.py
- src/static/js/aids/duplicate_buster.js
- Recherche les doublons parmi les aides non publiées
- Lance la recherche dés l'affichage du formulaire d'admin
- Copie le message d'erreur en haut du formulaire pour le rendre plus visible
- N'affiche plus l'aide actuelle dans la liste des doublons
>  Améliore l'outil de détection de doublons en admin

- src/static/css/_custom.scss
- src/templates/aids/detail.html
https://trello.com/c/yP8DnSnD/907-affichage-responsive-des-logos-sur-les-fiches-aides-et-ajout-du-lien-vers-page-porteur
- Modification de la `max-width` des logos sur la page `AidDetail` pour uniformiser les tailles et améliorer l'affichage responsive
- Ajout sur le logo du lien vers la page `porteurDetail`.
> Affichage responsive des logos sur les fiches aides et ajout du lien vers page porteur

- src/dataproviders/management/commands/import_dreal.py
- src/dataproviders/management/commands/import_grand_est.py
- src/dataproviders/management/commands/import_loire_bretagne.py
- src/dataproviders/management/commands/import_occitanie.py
- src/dataproviders/management/commands/import_rmc.py
A chaque run de l'import API Occitanie, il y a des bugs remontés.
https://sentry.io/organizations/aides-territoires-beta/issues/2013099544/
Plus précisément : le nom du porteur d'aide a dû changer, et la query Backer.objects.get() plante.
> Import API : résolution du bug remonté pour l'Occitanie

- src/programs/views.py
- src/templates/programs/detail.html
94 requêtes SQL étaient faites sur les pages `programDetail` pour afficher la liste des aides associées.
Reprise du code pour passer à 10 requêtes SQL.
> Réduit le nombre de requêtes SQL sur les pages programme

- src/locales/fr/LC_MESSAGES/django.po
- src/static/css/_custom.scss
- src/templates/aids/_base_search.html
- src/templates/aids/_search_form.html
https://trello.com/c/YVXRXlxe/897-ajout-du-filtre-programme-dans-le-cartouche-de-recherche
Ajout du filtre programme dans le cartouche de recherche. 
Suppression du filtre AAP/AMI.
Redesign du cartouche de recherche en 4 colonnes.
> Ajout du filtre programme dans le cartouche de recherche

- src/templates/aids/_search_form.html
Correction d'un bug liée à la PR #372 : le filtre programme demeurait dans la query malgré sa suppression du formulaire : 
- suppression de la ligne `{{ form.programs.as_hidden }} `dans le fichier _search_form.html
> Bug : le filtre program restait dans l'url malgré sa suppression du formulaire.

- .github/workflows/ci.yml
- deployment/roles/appservers/tasks/database.yml
- src/geofr/api/views.py
- src/scripts/first_deploy.sh
La recherche de périmètre (dans l'autocomplétion) est désormais insensible aux accents.
**NOTE IMPORTANTE** pour mes distingués collègues !
La fusion de cette PR va vraissemblablement rendre votre connexion à votre base invalide, car Postgres se plaindra qu'il manque l'extension « unaccent ».
Pour résoudre ce problème, il suffit de se connecter à la BD et d'activer l'extension.
> psql aides
> aides=# CREATE EXTENSION unaccent;
>  Recherche de périmètres sans accents

- src/aids/tests/test_views.py
- src/aids/views.py
Ajoute « [Copie] » devant le nom des aides dupliquées en frontend.
> Préfixe le nom des aides dupliquées

- src/aids/api/serializers.py
- src/dataproviders/management/commands/import_ademe.py
Parfois un string était concaténé à la liste des targeted_audiences
Ce qui provoquait des valeurs comme `['r', 'commune', '_', 'a', 'department', 'epci', 'o', 'private_sector', 't', 'private_person', 'n', 'p', 's', 'association', 'region', 'i', 'e', 'public_cies', 'researcher', 'v']`
Et in fine des erreurs lors d'appels API
https://sentry.io/organizations/aides-territoires-beta/issues/2167241639/?project=5506889&query=is%3Aunresolved
> Import ADEME : bug sur le bénéficiaires pour certaines aides

- src/analytics/management/commands/matomo_export_stats.py
- src/analytics/utils.py
Rendre le script réutilisable pour plusieurs méthodes Matomo (et non juste PageUrls comme avant).
Ca m'a permis de récupérer getSiteSearchKeywords sur l'année 2020
> Amélioration du script d'export Matomo

- src/static/js/aids/toggle_aid_instructor_field.js
- src/static/js/backers_autocomplete.js
- src/templates/aids/_base_edit.html
Supprime le contrôle javascript qui affiche un lien quand aucun résultat n'est trouvé dans l'autocomplétion, et affiche un simple champ « suggérer un nouvel apporteur » dans le formulaire.
> Simplifie la suggestion de nouveaux apporteurs sur le formulaire d'édition

- src/locales/fr/LC_MESSAGES/django.po
- src/minisites/urls.py
- src/templates/minisites/backer_detail.html
Dans la continuité du hotfix de la dernière fois
https://github.com/MTES-MCT/aides-territoires/commit/c4c0e04262824114bcdaec470a0a41ab23cbe4eb#diff-c649d0f828ee7e96d1c279a4d1261f590dc07dfcfa00c5aef148569364a86298
Répare 
- url complètes des backers
- breadcrumbs sur le template d'un backer
> Minisites: fix sur les urls des porteurs

- src/locales/fr/LC_MESSAGES/django.po
Ajout de la traduction de `Copy the current url to clipboard` perdue lors du merge précédent.
> Ajout d'une traduction manquante dans django.po

- src/accounts/admin.py
Évite de bloquer l'enregistrement du formulaire « inline » sur le module d'admin « utilisateurs » quand des champs noms ou prénoms sont manquants.
> Permettre l'enregistrement des modifs sur la page "utilisateur"

- src/static/js/aids/perimeter_autocomplete.js
- src/templates/aids/advanced_search.html
Certains périmètres "custom" ont été cachés de l'autocomplete dans https://github.com/MTES-MCT/aides-territoires/pull/384
Mais on souhaite quand même tous les avoirs dans les parties admin & porteurs du site.
Du coup l'action de filtrage a lieu seulement sur la partie utilisateur du site (étape 2 de la recherche, formulaire de recherche & recherche avancées)
> Selection périmètres cachés depuis formulaire de création d'aide

- src/Pipfile.lock
- src/alerts/management/commands/send_alerts.py
Suite de https://github.com/MTES-MCT/aides-territoires/pull/430
@lazybird j'ai laissé ActStream. Je te laisse me dire si on laisse le packet + l'app, ou si on enlève tout
> Log d'email alerte : utiliser sentry plutôt que actstream

- src/.buildpacks
- src/Pipfile.lock
Il semble que la version pip qui est utilisée sur scalingo ne marche pas pour installer la nouvelle version de cryptography.
> Changer la version et pip pour Scalingo

- src/static/css/_custom.scss
- src/templates/backers/detail.html
https://trello.com/c/3WJKMGeM/982-fixer-laffichage-du-titre-et-du-logo-sur-les-pages-porteurs-daides
Sur la page détail porteur, quand le nom du porteur était trop long, le logo en face se plaçait sans élégance en dessous. 
Fix ce problème en utilisant la grid bootstrap.
> Fix l'affichage du titre et du logo sur les pages backer-detail

- src/aids/forms.py
Avec ce changement, on rajoute des requêtes supplémentaires à la recherche, mais c'est pour s'assurer qu'on n'exclue pas des aides locales alors que leur version générique est absente.
> Certaines aides locales sont exclues par erreur sur les PP

- src/upload/management/commands/copy_to_bucket.py
Ce nouveau script permet de copier tous les fichiers medias connus sur un nouveau bucket Scaleway.
Usage : 
```
python manage.py copy_to_bucket <nouveau-bucket> https://<nouveau-bucket>.s3.fr-par.scw.cloud
```
> Copie tous les fichiers média sur un nouveau bucket

- src/templates/aids/_results.html
Historiquement l'affichage des programmes parmis les résultats des aides était prévu dans le template `_results.html. `
L'affichage n'était cependant pas effectif car programs n'était pas servi par SearchView. 
Avec l'ajout de `context['programs']` dans la `def get_context_data`, les programmes se retrouvent effectivement affichés. 
On modifie le template` _results.html` pour supprimer l'affichage des programmes dans la liste des résultats des aides.
> supprimer l'affichage des programmes dans la liste de résultats des aides

- src/templates/aids/_base_edit.html
Les champs `subvention-rate `et `subvention-comment` étaient placés trop bas das le formulaire. On les rapatrie juste en dessous du champ  `aid-types` pour plus de cohérence.
> Déplace le champ taux de subvention dans le formulaire d'aide

- src/templates/search/step_audience.html
- src/templates/search/step_perimeter.html
- src/templates/search/step_project.html
- src/templates/search/step_theme.html
Il manquait quelques `action=search` sur certaines étapes du formulaire de recherche.
Ca permettra un jour de filtrer les stats de recherche par `search` (formulaire), `search-filter` (cartouche), `search-details` (filtres avancés)
> Ajout des params 'action' dans les étapes de recherches

- src/dataproviders/utils.py
https://trello.com/c/Cmn8Qf6r/969-ouverture-des-liens-externes-dans-un-nouvel-onglet
On permet dans l'admin de forcer l'ouverture du lien dans un nouvel onglet. L'ouverture du lien sur la même page restera tout de même le comportement par défaut. Il faudra cliquer sur "visualiser le html" puis ajouter dans la balise <a> `target="_blank" rel="noopener"` pour que le lien change de comportement.
> Possibilité de forcer l'ouverture des liens externes dans un nouvel onglet

- src/search/tests/test_utils.py
- src/search/utils.py
Parfois il y a des querystring qui contiennent des périmètres au mauvais format. Modification pour fail silently lors du matching de Périmètre.
Exemple de bug remonté : https://sentry.io/organizations/aides-territoires-beta/issues/2252581325/
> Eviter des erreurs de matching de Périmètres pour les stats de recherches

- src/aids/templatetags/aids.py
Certaines aides (en brouillon, importées par exemple) ont `aid_types = None`
Ce qui fait planter le template lorsqu'on souhaite les afficher à partir de l'admin
Exemple : https://staging.aides-territoires.beta.gouv.fr/aides/be29-aide-au-developpement-des-cooperatives-dactiv/
> Répare l'affichage d'aides qui ont des choices vide

- src/accounts/tasks.py
- src/aids/tasks.py
- src/alerts/management/commands/send_alerts.py
- src/alerts/tasks.py
- src/emails/utils.py
- src/locales/fr/LC_MESSAGES/django.po
Tags définis : 
- `alerte` pour `send_alert()`
- `alerte_confirmation` pour `send_alert_confirmation_email()`
- nouvelle méthode `send_email()` qui utilise AnyMail derrière
- renommage de `send_template_email()` en `send_email_with_template()` 😬
> Ajout des tags Sendinblue pour les emails d'alerte

- src/stats/migrations/0009_aidsearchevent_populate_text.py
- src/stats/utils.py
S'assurer que les valeurs du champ `text` sont au max 256 chars
> Répare le stockage du champ 'text' du modèle AidSearchEvent

- src/templates/aids/_base_edit.html
Suite à la refonte du formulaire d'aide il a été décidé de supprimer le `field` `france_relance` dans le formulaire.  
Mais certaines aides ont besoin de continuer à être tagguées "France Relance" (ex: le site du MTFP utilise ce champ pour filtrer les aides). 
On ajoute donc le champ` france_relance` en champ caché dans le formulaire pour permettre l'édition des aides déjà crées sans perte du tag.
> Bug: ajout du champ france_relance.as_hidden dans le formulaire d'aide

- src/.buildpacks
Nous étions en attente de cette mise à jour qui a été mergée : https://github.com/Scalingo/python-buildpack/issues/14
> Mise à jour du buildpack python pour Scalingo

- deployment/roles/appservers/tasks/cron.yml
Provoquait trop de doublons et d'erreurs, car scraping & absence d'url unique pour certaines aides
> Arrêt de l'import Occitanie

- src/minisites/views.py
- src/templates/minisites/stats.html
Certaines PP n'affichent pas certains filtres de recherche (par exemple bénéficiaires ou sous-thématiques). Donc ne pas afficher les stats correspondantes
> Stats PP : cacher les stats des filtres non séléctionnés

- src/templates/aids/detail.html
https://trello.com/c/Df0AnMHT/1050-il-manque-lemail-pour-le-lien-contacter-at-dans-la-page-daide
> Ajout de l'adresse mail d'AT sur le bouton contact

- src/aids/forms.py
- src/aids/tests/test_forms.py
- src/core/fields.py
https://trello.com/c/0cdcm6il/1043-taux-min-de-subvention-non-obligatoire
> Permet de mettre uniquement un taux de subvention min dans le formulaire d'aide

- src/aids/resources.py
- src/backers/admin.py
- src/backers/resources.py
Rend possible l'export de l'ensemble des porteurs au format cvs/xlsx depuis l'admin avec les champs non présents dans le model.
> Ajoute la possibilité d'exporter les porteurs avec le nombre d'aides financées et/ou instruites

- src/accounts/admin.py
- src/aids/admin.py
- src/locales/fr/LC_MESSAGES/django.po
- src/templates/admin/accounts/user/change_form.html
Dans l'admin, affiche un compteur qui indique le nombre d'aides (en revues ou publiées) par le même auteur.
Affiche également la liste de ces aides.
> Affiche le nombre d'aides publiées par le même auteur

- src/dataproviders/utils.py
- src/static/js/shared_config.js
On force le comportement par défaut des liens quand ils sont ajoutés depuis l'admin : Tous les liens ajoutés depuis l'éditeur de texte s'ouvriront par défaut dans un nouvel onglet.
> Ouverture des liens ajoutés depuis l'admin dans un nouvel onglet

- src/scripts/post_deploy.sh
- src/scripts/start.sh
C'est un problème avec la persistance des fichiers sur les containers Scalingo. Il faut régénérer les fichiers "static" au moment de chaque redémarrage.
> Bug Scalingo : Au redémarrage, on perd les "static assets"

- src/aids/templatetags/aids.py
- src/aids/views.py
- src/search/tests/test_utils.py
- src/search/utils.py
- src/templates/aids/_search_meta.html
- src/templates/aids/detail.html
- src/templates/alerts/_alert_modal.html
Faire en sorte de récupérer les détails de la recherche sur d'autres pages que la recherche, pour pouvoir : 
- avoir ces filtres au moment de la création de l'alerte sous une fiche aide
- futurs usage (noter la pertinence d'une aide par rapport à la recherche / le projet choisi)
- afficher un message si il n'y a aucun filtre séléctionné
Où ca coincait : 
- impossible de sérialiser (pour stocker dans la session) le dict AidSearchForm
- la querystring plate contient des slugs, des ids ou des mots en anglais, pas pratique pour afficher ces infos dans l'interface, du coup il nous faut repasser par le formulaire pour cleaner la donnée
> Avoir les détails de la recherche dans AidDetailView (pour les alertes)

- src/locales/fr/LC_MESSAGES/django.po
- src/minisites/views.py
- src/static/css/_custom.scss
- src/static/css/_globals.scss
- src/templates/aids/draft_list.html
- src/templates/minisites/stats.html
- src/templates/stats/stats.html
Stats PP : 
- remplacer Matomo par nos stats depuis la db AidSearchEvents
- cleanup des traductions
> Stats PP : remplacer Matomo par notre db (AidSearchEvents)

- src/alerts/models.py
- src/alerts/tests/test_alert_command.py
- src/dataproviders/data/nouvelle_aquitaine_rss_categories_mapping.csv
- src/dataproviders/management/commands/import_pays_de_la_loire.py
- src/templates/alerts/alert_body.txt
Dans nos stats de recherche (AidSearchEvent), on est capable de détecter 3 'sources' (info qu'on peut extraire de la querystring) : 
- `action=search` = recherches classique
- `action=search-filter` = cartouche
- `action=search-filter-advanced` = recherche avancée
Mais il y a certaines recherches "fantôme" qui ne contiennent pas cette info. Je propose donc de rajouter `action=alert` dans les liens envoyés via les alertes. @SarahRubio on en avait discuté un peu il me semble
> Détecter les recherches effectuées à partir d'une url d'alerte

- src/aids/admin.py
- src/backers/admin.py
- src/backers/models.py
- src/geofr/admin.py
Quick fix pour se simplifier la vie quand on a seulement connaissance de l'id du Perimeter.
J'ai fait de même pour Aid & Backer.
> Admin : pouvoir chercher les Aides & Périmètres par id

- src/core/settings/production.py
- src/core/settings/scalingo.py
https://trello.com/c/2J3jp8E3/1133-make-css-vs-make-fullcss
Comme indiqué par Thibault, la commande `make fullcss` à la différence de la commande `make css`, génère les fichiers css à partir des fichiers scss ET génère les préfixes (`-moz-, -wk-, -ms-`) quand c'est nécessaire. Dans l'environnement local, cette commande est remplacée par "make css" pour des raisons de performances. 
- Ajout d'un commentaire expliquant cette commande dans les fichiers `production.py` et `scalingo.py`
- Passage à "`make fullcss`" dans le fichier `scalingo.py`
> Remplace "make css" par "make fullcss" dans la config scalingo

- .github/workflows/ci.yml
- src/Makefile
- src/Pipfile
- src/Pipfile.lock
- src/core/settings/test.py
Les actions mises en place :
- configuration plus précise de l'utilisation du cache dans les settings Github actions
- cache complet du virtualenv pour complètement squizzer l'installation des dépendances python
- installation d'un plugin pour lancer les tests en parallèle
- quelques petites optimisations techniques mineures
> Accélère les tests avec l'intégration continue

- src/templates/aids/_base_search.html
https://trello.com/c/VVKRiZYe/1142-utilisation-du-mot-r%C3%A9sultat-au-singulier-si-un-seul-r%C3%A9sultat
> Utilisation du mot "résultat" au singulier si un seul résultat pour la recherche

- src/aids/forms.py
- src/minisites/views.py
- src/search/models.py
On minisites, we want to run the generic/local aid filtering
when we combine the form filter, not on the initial queryset filtering.
This is the avoid that we prematurally exclude some aid that should be
collected when the user changes the form search parameters.
> Bug PP affichage aides locales

- src/core/tasks.py
- src/stats/admin.py
- src/stats/tasks.py
Actuellement les bizdev (e.g. Alexia) checkent tous les mois le nombre d'aides "live" sur la plateforme. Cette valeur est ensuite stockée dans un Excel, et nos slides sont mise à jour.
L'idée est de stocker cette valeur dans notre table `Event`
- on rajoutera d'abord à la main les valeurs anciennes (cf l'excel)
- on définira un cron qui lancera cette commande (tous les lundis ? tous les 1er du mois ?)
Ca nous permettra enfin de créer facilement un graphique de l'évolution du nombre dispo sur notre page stats.
> Tâche pour stocker le nombre d'aides disponibles

- src/aids/models.py
- src/dataproviders/scrapers/grand_est.py
- src/dataproviders/scrapers/occitanie.py
- src/dataproviders/scrapers/rmc.py
- src/dataproviders/tests/test_utils.py
- src/dataproviders/utils.py
Dans le nettoyage des données importées, accepte les balises « a ».
Pour éviter de casser les liens, transforme les urls relatives en urls absolues.
> Affiche les liens externes dans les imports

- src/eligibility/admin.py
- src/locales/fr/LC_MESSAGES/django.po
Admin : 
- fix la possibilité de sauvegarder un test avec les champs introduction & conclusion vide
- rajoute le nombre de résultats (nombre de tests effectués)
> Test d'éligibilité : fix dans l'admin

- src/static/css/_custom.scss
- src/templates/aids/_aid_result.html
- src/templates/aids/detail.html
- src/templates/minisites/_css.html
Page de résultats : 
- bouton toujours en bas
- lien clickable
Page d'aide : 
- bouton aligné à gauche (et non au centre)
> Test d'éligibilité : améliorer l'UI des boutons

- src/static/css/_custom.scss
- src/templates/aids/detail.html
https://trello.com/c/m7Vooixt/1102-masquer-la-liste-des-ss-th%C3%A9matiques-sur-la-fiche-aide
S'il y a plus de 4 thématiques liées à la fiche aide alors on affiche seulement les 4 premières ainsi qu'un bouton permettant d'afficher les suivantes.
> Masquer la liste des thématiques sur la fiche aides si > 4

- src/core/admin.py
- src/stats/admin.py
Ajout d'une méthode pour afficher de façon propre/joli les champs JSONField dans l'admin.
Visible dans Stats > AidEligibilityTestEvent
> Affichage propre des JSONField dans l'admin

- src/stats/tasks.py
Dans la continuité de https://github.com/MTES-MCT/aides-territoires/pull/566 , amélioration de la tâche pour aussi stocker le nombre d'aide dispo pour chaque PP. La tâche est lancée tout les Lundi midi.
Cela permettra dans Metabase d'avoir : 
- le nombre d'aides disponible qui soit le plus récent possible
- pouvoir tracer une courbe avec l'évolution de ce nombre
> Tâche pour stocker le nombre d'aides disponibles sur chaque PP

- src/aids/forms.py
- src/aids/tests/test_search_engine.py
- src/alerts/management/commands/create_alerts_from_csv_file.py
- src/alerts/tests/test_alert_create_command.py
- src/core/README.md
- src/core/__init__.py
- src/emails/__init__.py
- src/exporting/README.md
- src/exporting/__init__.py
- src/logs/README.md
- src/logs/__init__.py
- src/upload/README.md
- src/upload/migrations/__init__.py
Il y avait pas mal de warnings qui s'affichaient lorsqu'on lançait les tests (cf ci-dessous). Quelques modifs pour en enlever la plupart. Le reste dépendent de certains packets utilisés il semblerait.
```
../../../../../.local/share/virtualenvs/src-sTPXRt_8/lib/python3.7/site-packages/actstream/signals.py:4
/Users/ming-li/.local/share/virtualenvs/src-sTPXRt_8/lib/python3.7/site-packages/actstream/signals.py:4: RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
'description', 'timestamp'])
../../../../../.local/share/virtualenvs/src-sTPXRt_8/lib/python3.7/site-packages/django/apps/registry.py:91 …
```
> Tests : fix pour éviter certains warnings

- src/aids/admin.py
- src/aids/resources.py
Lors de l'update des aides pour leur associer un projet depuis un import csv, un bug pouvait potentiellement apparaître si l'aide n'avait pas d'auteur (L'onglet aides de l'admin devenait inaccessible après l'import réalisé car le champ `author` était vide).
> Bug lors de l'update des aides depuis un fichier csv si l'aide n'a pas d'auteur

- src/Pipfile
- src/Pipfile.lock
- src/aids/api/views.py
- src/aids/views.py
- src/minisites/views.py
- src/stats/tests/test_utils.py
- src/stats/utils.py
On a pas mal de stats inexpliquées. On se dit que ca vient surement de crawlers. Au vue des logs Scalingo, il y en a très régulièrement
```
// exemples de User Agents
"Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
"Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)"
"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
"Koj Bot"
"Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot)"
"Slack-ImgProxy (+https://api.slack.com/robots)"
"datagnionbot (+http://www.datagnion.com/bot.html)"
```
> Eviter de logger les stats provenant des crawlers

- src/minisites/urls.py
Certaines stats sur les PP (AidContactClickEvent & AidEligibilityTestEvent) n'étaient pas envoyés en base. Erreurs 404 car l'url n'était pas présente dans le `urls.py` de l'app minisites
> Répare l'envoi de certaines stats sur les PP

- src/accounts/admin.py
- src/accounts/models.py
- src/aids/admin.py
- src/aids/api/views.py
- src/core/settings/base.py
- src/core/urls.py
- Ajout de `TokenAuthentication` dans django-rest-framework
- L'authentification permet seulement de savoir qui fait la requête, on ne bloque pas les requêtes pour l'instant (il faudrait basculer les permissions à `IsAuthenticated`)
- Dans l'admin, nouvelle "app" Token qui permet d'assigner un token à un utilisateur
- Dans l'admin coté Utilisateur, on peut filtrer par ceux qui ont un token. Et ce token est affiché en read-only dans leur infos
Reste à faire : 
- ~avoir des stats d'usage par utilisateur de l'API~ (plus tard)
> Authentifier les utilisateurs de l'API avec un Token

- src/aids/forms.py
https://trello.com/c/MHmqXGJo/970-rendre-le-champ-type-daide-obligatoire
> Rend le champ "type d'aide" obligatoire dans le formulaire de demande de publication d'une aide

- src/core/urls.py
- src/locales/fr/LC_MESSAGES/django.po
Petite PR qui renomme simplement : 
- le titre de l'admin
- le sous-titre
- le nom de la page (en passant la souris sur l'onglet)
> [Customization de l'admin] Renomme les titres

- src/geofr/api/serializers.py
- src/geofr/api/views.py
https://trello.com/c/xJeFzYOk/1249-prendre-en-compte-les-codes-postaux-dans-la-recherche-du-territoire-%C3%A0-l%C3%A9tape-de-recherche
> Autocomplétion du périmètre de recherche à partir du code postal 

- src/alerts/tests/test_alert_command.py
- src/search/forms.py
- src/search/tests/test_forms.py
Ajout de 'show_backers_field' pour comptabiliser le nombre de filtres à afficher dans le cartouche des PP.
> Mise à jour de la fonctionnalité de contrôle du nombre de filtres de recherches dans les PP

- src/admin_lite/mixins.py
- src/aids/admin.py
- src/search/admin.py
We use to check the user's group in order to grant these permissions.
With this change, the permissions to the admin pages are granted
automatically. This saves a extra configuration setp, since we don't
have to add the user to a group anymore.
> Administrateur de PP: On ne devrait pas avoir à ajouter l'utilisateur dans un groupe

- src/core/urls.py
2 endpoints maintenant : 
- `/swagger` (actuel)
- `/redoc` (pour tester et comparer)
> API : ajoute redoc comme alternative à swagger

- src/backers/api/views.py
On garde juste la possibilité de lister tous les porteurs
> API : enlève l'endpoint de détail d'un porteur d'aide

- src/aids/api/views.py
- src/backers/api/views.py
- src/core/api/pagination.py
- src/geofr/api/views.py
- src/programs/api/views.py
Il y avait déjà l'argument size sur l'endpoint `/aids`.
On rajoute ce mécanisme aux endpoints `/backers`, `/perimeters` et `/programs`
> API : ajout de l'argument size sur des endpoints additionnels

- src/minisites/views.py
La page stats de la PP petitesvillesdedemain rencontrait un timeout dû à une requête sql trop lourde. En conséquence le container aides-terr-pp renvoyait un application error et entrainait un gros ralentissement de toutes les autres PP. 
C'est la query pour afficher le top 10 des catégories les plus recherchées qui était en cause.
> Fix bug affichage page stats de la PP petitesvillesdedemain

- src/templates/_header.html
- src/templates/home/home.html
Le nouveau nom des pages personnalisées n'est plus "mini-sites" mais "portails"
> Remplacer "mini-sites" par "portails"

- src/aids/constants.py
Sur la page de détail des aides, les différentes aides en ingénieries n'apparaissait pas avec un nom assez univoque ce qui pouvait amener à une confusion. 
Ex: si l'aide était une aide en ingénierie financière apparaissait "financière" laissant penser que l'aide n'était pas une aide en ingénierie mais bien une aide financière. 
https://trello.com/c/FPdYd4LF/1365-175-probl%C3%A8me-daffichage-du-nom-des-aides-en-ing%C3%A9nierie
> Renommer les différentes aides techniques pour éviter toutes confusions avec les aides financières

- src/aids/api/serializers.py
- src/backers/api/serializers.py
- src/core/api/doc.py
- src/core/settings/base.py
- src/geofr/api/serializers.py
Ajout du champ `is_call_for_project` dans le serializer d'aides
Améliore la documentation en présentant les changements entre les versions
Ajoute le nom des champs dans la doc des aides
> API : v1.4

- src/Pipfile.lock
Le merge de [la Pull request 781](https://github.com/MTES-MCT/aides-territoires/pull/781) a introduit un bug empêchant le déploiement sur scalingo : 
`[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for openpyxl==3.0.8 (from -r /tmp/pipenv-18uuodjq-requirements/pipenv-1_3kimnq-requirement.txt (line 1))
ERROR: Couldn't install package: openpyxl
Package installation failed...`
On revient donc sur la version précédente du fichier Pipfile.lock
> Fix du fichier Pipfile.lock

- src/aids/models.py
- src/aids/views.py
- src/templates/aids/detail.html
Deux erreurs existaient sur le sujet : 
1. L'utilisateur chercheur d'aide mais pas porteur d'aides avait la possibilité de cliquer sur le bouton "dupliquer cette aide" sur la page de détail d'une aide nationale.
2. Si une aide nationale avait été associée à un projet la duplication de l'aide en aide locale créé un bug lié au clone du champ M2M `projects`.
> FIx : duplication d'une aide générique en aide locale quand l'aide a été associée à un projet

- src/accounts/views.py
L'accès à la page collaborators ne renvoyait pas l'utilisateur non authentifié vers la home mais créait une erreur 500.
> Fix : accès à la page collaborators 

- src/templates/home/contact.html
https://www.notion.so/Ajouter-une-mention-sur-la-page-Contact-pour-dire-qu-on-ne-fait-pas-de-conseil-d34e220fed914ab595f7508e62519b45
> Page Contact : ajouter un block info indiquant qu'AT ne fait de conseil

- src/static/css/_globals.scss
- src/templates/aids/detail.html
https://www.notion.so/Fix-design-champ-Url-d-origine-sur-les-pages-d-tail-aide-aac3b5892ff741faae058c4e3a5910ce
> Fix design : champ 'Url d'origine' sur les pages détail aide

- src/templates/aids/_base_search.html
- src/templates/minisites/search_page.html
- src/templates/search/general_search.html
Ajout des balises Og sur les pages = 
- trouver des aides
- résultats aides
- page portails (balise og:image à fixer)
https://www.notion.so/Ajout-des-balises-OG-manquantes-ae079e3010084fc5ac6000d424b587b4
> Ajout des balises OG manquantes

- src/search/forms.py
https://www.notion.so/Remettre-intercommunalit-plut-t-que-epci-fiscalit-propre-sur-la-page-trouver-des-aides-e525aed49be941eabd5de1460ec89e8d
> Trouver des aides : amélioration des options du champ "bénéficaire"/targeted_audience 

- src/templates/aids/_search_form.html
https://www.notion.so/BUG-Pb-lorsqu-on-veut-cumuler-dans-une-recherche-des-filtres-plus-de-crit-res-avec-des-filtres-d-88cffd045e2a461f8cc359d194492d75
> Conserver le filtre 'appel à projets' lorsque la recherche est complétée depuis le cartouche

- src/templates/projects/project_detail.html
https://www.notion.so/10d46008805d4aa89747ea969180b828?v=a2925c6c61874655ac01a13b4de10b59&p=6aedab302b54457aaf8319ee4a79b7bd
> Afficher uniquement le nom du collaborateur sur la page de détail d'un projet

- src/accounts/factories.py
- src/accounts/forms.py
- src/accounts/tests/test_views.py
- src/accounts/utils.py
- src/conftest.py
- src/templates/accounts/contributor_profile.html
cf https://www.notion.so/V-rifier-le-mot-de-passe-de-l-utilisateur-avant-de-lui-permettre-de-le-changer-f446147dcb414e9ca7efd33eab68a07f
- Ajout d'une vérification du mot de passe de l'utlisateur avant changement de celui-ci
- Correction de plusieurs tests liés aux comptes utilisateurs.
> Vérifier le mot de passe actuel de l'utilisateur avant de lui permettre de le changer

- .github/workflows/ci.yml
- src/Pipfile
- src/Pipfile.lock
https://www.notion.so/Mettre-jour-les-d-pendances-de-Python-fa32ef737389427abd6a237a76111ccf
Il y a plusieurs alertes de sécurité signalées sur Github et liée à des dépendances de Python → il faut mettre à jour ces paquets.
De plus, la CI se fait sur une version de Python (3.8) différente de celle installée sur la production (3.6.13) → il faudrait uniformiser ça et utiliser la même sur nos machines de dev. La doc de Scalingo dit que la version supportée la plus récente est Python 3.10.1, je propose de partir là-dessus (cf. [https://doc.scalingo.com/languages/python/start](https://doc.scalingo.com/languages/python/start) )
> Pipfile update obsolete

- src/templates/aids/detail.html
https://www.notion.so/Dans-la-fiche-aide-remplacer-l-acronyme-AAP-AMI-par-Appel-projets-AAP-Appel-manifestat-8e2b6cc6025d4a2c921e2de1d969d58b
> Fiche Détail des Aides : Remplace les acronymes AAP/AMI par les noms détaillés

- src/core/settings/base.py
- src/core/settings/local.py
Ajout d'une seconde entrée "TEMPLATE" dans les paramètres locaux (core/settings/local.py) pour permettre à django_debug_toolbar de fonctionner sans avoir à jongler entre elle et l'extension django_admin_tools qui a un paramétrage incompatible)
https://www.notion.so/La-debug_toolbar-ne-s-affiche-plus-caa5e9fd5ff641c68577ebc93c0d9e2f
> Ajout d'un second TEMPLATE dans les paramètres locaux

- src/templates/_header.html
https://www.notion.so/Mettre-un-lien-vers-les-stats-dans-le-menu-En-savoir-plus-1283060e05da44d2a6f574db84dd3a63
> Ajoute un onglet "statistiques" dans la barre de navigation principale

- src/templates/aids/detail.html
https://www.notion.so/Afficher-les-mots-cl-s-dans-la-page-d-tails-de-l-aide-4c03c54c6a0442888435e1926323a761
>  Affichage des sous-thématiques/mots clés associés à une aide sous forme de tag dans la page détail d'une aide

- src/aids/views.py
- src/templates/aids/detail.html
https://www.notion.so/Personnalisation-de-la-recherche-par-mots-cl-s-depuis-la-page-d-tail-d-une-aide-si-l-utilisateur-est-8930ad6ebc5c4022954b419fbf50e80e
> Personnalisation de la recherche par mots clés depuis la page détail d'une aide si l'utilisateur est connecté

- src/templates/projects/project_detail.html
https://www.notion.so/Ajouter-les-badges-li-s-l-ch-ance-de-l-aide-dans-le-tableau-des-projets-9c1be273c8d249aa89b6a9d4fd5d2a3a
> Ajouter les badges liés à l’échéance de l’aide dans le tableau des projets

- ONBOARDING.md
- src/conftest.py
La fixture `django_db_setup` est rendue inutile lorsqu'on applique la commande sur `template1` qui est le template par défaut pour créer la base de tests.
MAIS, il faut lancer la commande avec les bons paramètres, ce qui a conduit à modifier la documentation d'ONBOARDING.
> Correction de la documentation pour lancer des tests

- src/accounts/forms.py
- src/accounts/tests/test_views.py
- src/accounts/views.py
- src/organizations/views.py
- src/static/js/aids/perimeter_autocomplete.js
- src/templates/accounts/register.html
- src/templates/organizations/create.html
https://www.notion.so/Simplification-de-l-inscription-suppression-de-la-division-en-2-tapes-953c9e9c44b4467786603f95cb09bc8c
- Fusion du formulaire en deux étapes afin de faciliter l'inscription
- Mise à jour des tests correspondant à l'inscription
- Amélioration des tests avec utilisation d'une valeur issue de la liste `perimeters` pour le champ `perimeter` plutôt que l'utilisation d'un `id` dont l'existence n'est pas vérifiée (cela posait problème notamment dans le cadre du lancement de la commande `py.test --reuse-db`) >> cette partie a été réalisée avec @davidbgk :)
> Compte utilisateur : simplification de l’inscription (suppression de la division en 2 étapes) 

- src/core/settings/base.py
https://www.notion.so/Changer-l-URL-https-france-relance-mayotte-aides-territoires-beta-gouv-fr-en-https-mayotte--7bd00dfc15e14e40b05e2cc7f41aae5a
> Redirige france-relance-mayotte vers le portail mayotte

- src/accounts/views.py
Le message de succès lors de l'inscription à la newsletter était tronqué (en cause une mauvais gestion des retours à la ligne dans le code). L'utilisateur n'était donc pas informé qu'un email avec un lien d'activation, nécessaire à la finalisation de son inscription, lui était envoyé)
> Répare la fonctionnalité d'inscription à la Newsletter

- src/templates/_footer.html
- src/templates/blog/post_list.html
- src/templates/home/home.html
Permet de réduire le temps de chargement des pages, les images qui ne sont pas visibles sans scroller sont ainsi chargées uniquement lors du défilement lorsqu’elles deviennent visibles.
> Chargement des images non visibles en mode lazy

- src/static/js/aids/favorite_project_checkbox_required.js
- src/templates/aids/detail.html
- src/templates/projects/_suggest_aid_modal.html
- Ajout d'une condition pour vérifier que l'aide à suggérer n'est pas déjà associée au projet avant la soumission du formulaire
- Ajout d'une condition : au moins un projet favori doit être sélectionné avant soumission du formulaire
> Fix : suggérer une aide depuis la page détail d'une aide

- src/static/css/stats.css
- src/static/js/stats/map_controller.js
- src/stats/tests/test_views.py
- src/stats/views.py
- src/templates/stats/carto_stats.html
1. Affichage du nombre de communes/epcis ayant un compte par département lorsqu’on est à l’échelle de la commune
2. Utilisation d’une échelle de couleurs basée sur le pourcentage de communes ayant un compte par département (et affichage de ce pourcentage)
3. Passage du noir au violet pour les communes ayant potentiellement une incohérence
4. Réduction d’un bug CSS sur l’affichage de la légende
> Affichage données département + échelle en pourcents

- src/projects/admin.py
- src/projects/forms.py
- src/projects/views.py
- src/templates/projects/public_project_detail.html
Bug : réparer le formulaire de création de projet (champ appartenance à un plan/programme/contrat)
Bug : Autoriser les superuser à prévisualiser les projets publics dont le statut est en revu depuis le bouton 'voir sur le site' de django-admin
https://www.notion.so/Probl-me-de-pr-visualisation-des-projets-publics-3d7d65d548094367abbb33f55b98b3dd
https://www.notion.so/Bug-lors-de-la-s-lection-des-plans-programmes-contrats-lorsque-l-utilisateur-cr-e-un-projet-bcb88fcdc75a4cc1bcc12dfc63acddbf
> Réparation de petits bugs sur la fonctionnalité de publication des projets

- src/templates/aids/detail.html
https://www.notion.so/Bug-affichage-fiche-aide-74f1ef72a62844dd9820f224feb0040a
> Corrige un bug d'affichage sur la page detail d'une aide lorsque celle-ci n'a pas de critères d'éligibilités

- src/projects/forms.py
- src/static/js/aids/project_perimeter_autocomplete.js
- src/templates/home/home.html
- src/templates/projects/_project_search_form.html
- src/templates/projects/public_projects_list.html
Suite à l'implémentation du formulaire de recherches de projets sur l'accueil, le champ territoire du formulaire de recherche d'aides, également sur la page d'accueil était cassé. réparation en renommant le champ `perimeter` du formulaire de recherche de projets afin qu'il n'est pas le même nom que le champ présent pour la recherche d'aides.
> Réparer le champ de recherche "votre territoire" sur la page d'accueil

- src/stats/views.py
On veut une unicité de décompte pour un périmètre donné.
Il est possible qu'il y ait plusieurs organization de type commune et de périmètre commune, aussi on ajoute bien la distinction sur le périmètre.
> Uniformisation du décompte des communes/epci

- src/dataproviders/utils.py
Fix : l'ajout du span sr-only au tag a depuis l'admin ne vérifiait pas si ce span existait déjà.
https://www.notion.so/BUG-Contenus-suite-un-lien-hypertexte-l-outil-inscrit-automatiquement-Ouvre-une-nouvelle-fen-t-cb8d2007f97843f797521bde6fae98c9
> Fix : contrôle de l'ajout du span sr-only au tag a depuis l'admin

- src/aids/forms.py
- src/aids/tests/conftest.py
- src/aids/tests/test_workflows.py
- src/static/js/aids/duplicate_buster.js
https://www.notion.so/BUG-Formulaire-de-contribution-l-outil-signale-des-doublons-qui-n-en-sont-pas-8945b5567380488ea114e58353173d4d
L'outil de détection des aides en doublon depuis le formulaire de contribution en front été cassé : Une aide était considérée comme son propre doublon car le champ slug du formulaire (censé permettre une comparaison entre l'aide éditée et celle de la base ayant le même origin_url) avait disparu du form. Je le remets comme hiddeninput.
> Réparation de l'outil de détection des aides en doublon dans le formulaire de contribution

- src/geofr/api/serializers.py
Le champ "code" qui contient pour les communes le code INSEE n'était pas présent dans l'endpoint Perimeters ce qui complique les requêtes de nos partenaires. 
Ex Thibault Rouveyrol du projet https://lafrancedessolutions.gouv.fr/ : 
> On a un cas d'usage où on va renvoyer l'usager (un maire) sur votre site pour une recherche d'aide déjà filtré sur son territoire et ses thematiques.
> https://aides-territoires.beta.gouv.fr/aides/?targeted_audiences=commune&perimeter=%7B%7D&categories=%7B%7D%22
> Du coup on a besoin des variables perimeter et categories. Pour les categories, on va les recup grace à l'api https://aides-territoires.beta.gouv.fr/api/themes/
> Par contre pour les perimeter, c'est votre id interne qui identifie un territoire. De notre coté, on utilise le code INSEE pour …
> API : Ajout du champ 'code' à l'endpoint Perimeters

- src/static/js/aids/perimeter_autocomplete.js
- src/static/js/aids/project_perimeter_autocomplete.js
https://www.notion.so/Ajouter-du-texte-info-sur-le-champ-territoire-pour-accompagner-l-utilisateur-dans-l-inscription-b394775eaf754bf2a073b95223530aef
> Ajouter du texte info sur le champ “territoire” pour accompagner l’utilisateur dans l’inscription 

- src/stats/views.py
https://www.notion.so/R-parer-le-tableau-Aides-les-plus-populaires-sur-la-p-riode-dans-l-onglet-engagement-du-dashbo-adc7ddc72d48440fbff785e186574ca6
> Réparer le tableau “Aides les plus populaires sur la période …” dans l’onglet “engagement” du dashboard stats internes

- src/templates/programs/detail.html
https://www.notion.so/BUG-R-parer-l-affichage-du-nombre-d-aides-sur-les-pages-programmes-e263c2523c9e4fee88dcc31ed4044401
> Réparer l’affichage du nombre d’aides sur les pages programmes

- src/aids/forms.py
https://www.notion.so/R-parer-la-fonctionnalit-de-mise-en-avant-des-aides-sur-les-portails-c1b2ca4730894fd298b539d6f516614a?pvs=4
> Réparer l'affichage des aides mises en avant sur les portails

- src/templates/programs/_faq_program.html
https://www.notion.so/modifier-la-date-de-mise-jour-de-la-FAQ-en-ca-d-ajout-manuel-d-une-QA-sans-passer-par-l-import-6484f97e6cdc4238a64773c9ca42a3ca?pvs=4
> Modifier de la date de mise à jour de la FAQ en cas d’ajout manuel d’une QA sans passer par l’import

- src/aids/admin.py
https://www.notion.so/Afficher-les-projets-associ-s-une-aide-depuis-la-page-d-tail-d-une-aide-en-admin-6e8350f4c2fb438fa56e562956375978?pvs=4
> Afficher les projets associés à une aide depuis la page détail d’une aide en admin

- src/static/js/stats/chartist-plugin-tooltip.js
https://www.notion.so/chapper-les-caract-res-sp-ciaux-dans-les-infobulles-des-stats-c2dc544b7d4e4343949c84c65edfdf77?pvs=4
> Échapper les caractères spéciaux dans les infobulles des stats

- src/templates/_calendar_snippet.html
- src/templates/stats/_start_end_date_form.html
- src/templates/stats/dashboard_base.html
- src/templates/stats/organizations_stats.html
- src/templates/stats/projects_stats.html
- src/templates/stats/users_stats.html
https://www.notion.so/Bug-Retirer-le-doublon-de-l-ic-ne-calendrier-sur-les-champs-de-formulaire-f319529cfc634dd29bad6eef9fb6246c?pvs=4
> Bug - Retirer le doublon de l’icône calendrier sur les champs de formulaire

- src/alerts/management/commands/send_alerts.py
https://aides-territoires-beta.sentry.io/issues/4233110095/?project=5553558&referrer=slack
> Répare une erreur lors de l'envoi d'alerte lorsque la source de l'alerte n'est pas définie

- src/templates/aids/draft_list.html
https://www.notion.so/Dans-le-portefeuille-d-aides-du-contributeur-lorsqu-une-aide-est-expir-e-mettre-le-statut-Expir-e-418e72c4b2be4879b465afd1b08e1487?pvs=4
> Ajouter le statut "archivée" dans l'affichage du portefeuille d'aides

- src/templates/aids/detail.html
https://www.notion.so/Sur-les-fiches-aides-remplacer-le-titre-du-champ-Dispositif-applicable-pour-un-projet-par-tat-d-9b0f1afc9713411696b936ec6281944f?pvs=4
> Modifier le label pour le champ `mobilization_steps` sur la page détail des aides

- src/aids/forms.py
- src/static/css/_custom.scss
https://www.notion.so/Rendre-obligatoire-le-champs-type-de-d-penses_actions-couvertes-9cfa87b3221a48db83bf239d105158b6?pvs=4
> Rendre obligatoire le champ "type de dépense / action couverte"

- src/dataproviders/utils.py
https://www.notion.so/Pouvoir-ajouter-des-tableaux-dans-les-champs-textuels-du-formulaire-de-contribution-6b0377069f084d2da2f8ec0b96e9b160?pvs=4
> Autoriser l'ajout de tableaux dans les contenus rédactionnels

- src/static/css/_custom.scss
https://www.notion.so/Pouvoir-identifier-sur-la-page-de-r-sultats-si-on-a-d-j-consult-ou-non-une-aide-8fcfc8d6b11d4d7da3551e91eab6621a?pvs=4
> Pouvoir identifier sur la page de résultats si on a déjà consulté ou non une aide 
